### ISSUE TITLE
load more button missing in appoverview

### ISSUE THREAD

**Issue by JordanGerada3** [eclipse-tractusx/portal-frontend#1008]
### Current Behavior

Unlike service overview, app overview does not have a load more button. If the number of apps exceeds the default view size (15), apps other than the ones included in the default number of apps rendered are not accessible/viewable. 

### Expected Behavior

There should be a load more button available when there are more records available than show in the default list view, which continues to extend the view of apps until all apps are shown. 

### Steps To Reproduce

- login as a company admin
- Navigate to App Management tab -> App overview
- Observe missing load button (will only show if more than 15 apps available)

**Comment by oyo** [comment]
The load more button seems old fashioned to me. From mobile devices users are familiar with "load more on scroll to bottom" concept. For demonstration purposes I have implemented that once on the notifications page https://portal.int.catena-x.net/notifications (for example logged on as CX Operator) where the load is triggered once the end of the table comes into view saving an unnecessary click for the user.

@MaximilianHauer what is your take on that as PO?

**Comment by MaximilianHauer** [comment]
fair point but i would split this topic. 
the goal of jordan is to create quick consistency.
your proposal is to streamline everything to the state-of-the-art behavior. 

as we have many places where we have tables with a limit of initial roles i would create a new story where we list all of them and then focus on replacing the functionality in one go.
