### ISSUE TITLE
Marketplace | Subscribe App | Roles Requirement

### ISSUE THREAD

**Issue by typecastcloud** [eclipse-tractusx/portal-frontend#1012]
### Description
**As** Business Admin in Portal,
**I want** to be able to click on subscription button in App Marketplace,
**so that** I can subscribe to an app.

As defined by [permission matrix](https://github.com/eclipse-tractusx/portal-assets/blob/v2.1.0/public/assets/images/content/PortalRoleAndPermissionMatrix.png).

### Acceptance Criteria

- [ ] [As Business Admin I am able to subscribe to apps.]

### Additional Information
Currently both subscribe_apps and subscribe_service roles are required to subscribe to an app.

**Comment by MaximilianHauer** [comment]
thanks for the finding . pr needs a review from @oyo  and then we are good to go :)

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer 
I tested the this US According to requirements it's Working fine.

Attached Screenshots for References.
![image](https://github.com/user-attachments/assets/9eeba1e6-bbc1-4dfd-99c6-26e972fdc4d1)
![image](https://github.com/user-attachments/assets/aa84fed2-9f19-4197-ae66-2809130c3fb5)
