### ISSUE TITLE
ConnectorManagement - Managed Connectors - Detailpage not working

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1014]
### Current Behavior

if i try to open the details of a connector the page wont open 
![image](https://github.com/user-attachments/assets/d479b297-3d04-4ffe-ac8e-5dba892c5486)

### Expected Behavior

behavior should be identical to the behavior of "owned connectors" detail page 
![image](https://github.com/user-attachments/assets/9c39968d-dc60-47fd-accc-675920d7f277)

### Steps To Reproduce

1. go to `https://portal.int.catena-x.net/connectorManagement`
2. click `Managed Connectors`
3. Open `Details` of a connector

**Comment by manojava-gk** [comment]
@MaximilianHauer Could you pls help me to create a Managed connector?

**Comment by manojava-gk** [comment]
@MaximilianHauer GET connector details api is only available for owned connectors. Even in FE business logic, Lavanya has purposefully added the condition not to show details page for managed connectors.
Ideally details section should not be shown in the managed connector table.
Please confirm to proceed further

**Comment by MaximilianHauer** [comment]
issue will be solved implicitly by https://github.com/eclipse-tractusx/portal-backend/issues/944 
therefore i close it

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer 
I tested this issue its working fine now.

Attached Screenshots for References
![image](https://github.com/user-attachments/assets/0b28fa9a-5834-4b31-9e68-dad6cde2e1ff)
