### ISSUE TITLE
Serviceapi missing in CompanySubscription

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1015]
### Current Behavior

the app api is called two times but the service api is not 

![image](https://github.com/user-attachments/assets/80ad3884-d97a-477f-9960-92d5736fc955)

### Expected Behavior

`GET: /api/services/subscribed/subscription-status`should be called too

### Steps To Reproduce

1. Move to https://portal.int.catena-x.net/companySubscriptions
2. Check the calls
3. see that no service api is called

**Comment by MaximilianHauer** [comment]
@ybidois  we currently aim to split the view 
![image](https://github.com/user-attachments/assets/858d8f56-7ce5-4d41-91fc-b2a5fc944c30)

The endpoints used are currently 
```
/api/services/subscribed/subscription-status
/api/apps/subscribed/subscription-status
```
@manojava-gk  adjusted the wording according to your proposal. 
if something else is missing just get back to us

**Comment by ybidois** [comment]
Thanks @MaximilianHauer and @manojava-gk. Seems all good!

**Comment by gopalreddy-bmw** [comment]
@manojava-gk 
Api is called two times can you please look into it.

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer 
i Tested this issue know it's working fine Can you close this ticket.

Attached Screenshots for references:
![image](https://github.com/user-attachments/assets/e4b7d88a-4ca4-4054-ae60-eab24967115d)
![image](https://github.com/user-attachments/assets/15f2efee-730c-46b5-991e-f075e7bf6460)
