### ISSUE TITLE
ServiceSubscription - Activation ends in blank screen

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1016]
### Current Behavior

after confirm the page is ending in a blank page 

### Expected Behavior

jump back to https://portal.int.catena-x.net/serviceSubscription after successful creation 

### Steps To Reproduce

please be aware that this testcase needs to be resettet by phil/norbert before you can repeat it therefor activate your logging before testing it. if you need another try please ask phil. 

1. Login to Test 24_08
2. move to https://portal.int.catena-x.net/serviceSubscription
3. press configure in subscription 
4. press confirm

**Comment by evegufy** [comment]
@MaximilianHauer I suggest to close this issue

**Comment by MaximilianHauer** [comment]
tested and approved
