### ISSUE TITLE
Managed Connectors | "Details" link/CTA is not functional for Managed connectors

### ISSUE THREAD

**Issue by ss-nikunj** [eclipse-tractusx/portal-frontend#1017]
### Current Behavior
- Goto User Menu & Click on "Connectors Management"
- Switch to “Managed Connectors“
- Click on the “Details“ link for any existing connector under Managed Connectors 
- The “Details” link/CTA is not functional for Managed connectors.

### Expected Behavior
- It should be functional and lead to the expected/required detailed page like Owned Connectors
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/0d1c235a-913b-44bf-85c2-c08db8b9742f">

### Steps To Reproduce
- Goto User Menu & Click on "Connectors Management"
- Switch to “Managed Connectors“
- Click on the “Details“ link for any existing connector under Managed Connectors 
<img width="1246" alt="image" src="https://github.com/user-attachments/assets/022dbed2-f4d8-42da-886b-7cce70e697f7">

**Comment by MaximilianHauer** [comment]
@ss-nikunj  duplicate to https://github.com/eclipse-tractusx/portal-frontend/issues/1014 
we are working on this one already the adjustment you propose in the PR are not enough.

**Comment by evegufy** [comment]
Hi @ybidois @ss-nikunj  with reference to https://github.com/eclipse-tractusx/portal-frontend/pull/1018#issuecomment-2396342652: are you referring to the following overlay?:

![image](https://github.com/user-attachments/assets/954a0165-03ea-4e89-becc-3528547231fa)

cc: @MaximilianHauer

**Comment by ss-nikunj** [comment]
Hi @evegufy, 

Thank you for taking my comment into consideration.

To clarify, I was not referring to the overlay issue. The problem occurred when users attempted to click on the `Managed Connectors -> Detail Arrow Icon`, Where the detail overlay was not opening.

This issue was resolved by @lavanya-bmw two weeks ago in commit: 6a45e6a and Pull Request:  https://github.com/eclipse-tractusx/portal-frontend/pull/1142

CC: @ybidois 
> Hi @ybidois @ss-nikunj with reference to [#1018 (comment)](https://github.com/eclipse-tractusx/portal-frontend/pull/1018#issuecomment-2396342652): are you referring to the following overlay?:
> 
> ![image](https://private-user-images.githubusercontent.com/46191613/374631882-954a0165-03ea-4e89-becc-3528547231fa.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg0NDk0OTksIm5iZiI6MTcyODQ0OTE5OSwicGF0aCI6Ii80NjE5MTYxMy8zNzQ2MzE4ODItOTU0YTAxNjUtMDNlYS00ZTg5LWJlY2MtMzUyODU0NzIzMWZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDA5VDA0NDYzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWM0M2M2NmJjOTBlMjA2NmQ1MjRiNDgyM2E1Njg4ZTBjZmFkMjk4NjI2NGY0ZDg5Mjk0N2I0YjhkMjNhYzkzYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.fFrDm6QPAgKynDVHMfmNFQFF9uVyDbMTBtQin9Fe_nk)
> 
> cc: @MaximilianHauer
