### ISSUE TITLE
Service Release page, Validation for text fields in the Offer Card of Service Release Process is not working

### ISSUE THREAD

**Issue by saadanzari** [eclipse-tractusx/portal-frontend#1021]
Regex for offerCard is different than the error messages shown.

### Current Behavior
Validation errors are generated for valid input data

### Expected Behavior
Validation errors should not be generated for valid input data

### Steps To Reproduce

1. Log into the system with service manager/CX Admin
2. Navigate to the Service Release module.
3. Start creating or editing an Offer Card in Step 1.
4. Enter all valid special characters and spaces (including two consecutive spaces) in the text field./ Next line (Press Enter Key)
5. Note that the validation messages for text fields

![0119200b-4c72-4506-b677-13d643e99519](https://github.com/user-attachments/assets/515d2741-bf46-4217-abd9-0ac034e4dc98)

**Comment by MaximilianHauer** [comment]
good finding , do you create the PR ?

**Comment by charmi-v** [comment]
@MaximilianHauer There is another open [issue](https://github.com/eclipse-tractusx/portal-frontend/issues/965) and its associated [PR](https://github.com/eclipse-tractusx/portal-frontend/pull/993)

- The open PR modifies the regex validation for both short and long descriptions.
- Old Regex: Restricted specific characters and enforced certain rules (e.g., no two consecutive spaces or special characters).
- New Regex: Allows any characters as long as the string length is between 10 and 120 characters.

If the solution in the open PR is deemed appropriate, merging it will directly resolve the current issue. However, if there is a requirement for specific rules in the regex validation, please share the criteria considered for validating the short and long descriptions to ensure the regex update meets those needs.

**Comment by MaximilianHauer** [comment]
ok then lets wait for the pr to be adjusted (small finding their) and then we are good to go

**Comment by MaximilianHauer** [comment]
pr is merged @charmi-v  / @saadanzari  i assume we can close this one ?

**Comment by charmi-v** [comment]
@MaximilianHauer  The updated regex has a limitation: it allows users to enter a description consisting only of spaces.
It would be better to validate that the description should not consist solely of spaces and update the error message for the user as follows:
Old message: "Valid characters include a-zA-ZÀ-ÿ0-9 !?@&#'"()_-=/*.,;:"
New message: "Valid characters include a-zA-ZÀ-ÿ0-9 !?@&#'"()_-=/*.,;:. Spaces alone are not allowed."

**Comment by MaximilianHauer** [comment]
good point but if someone would like to provide a bad explanation he could just enter "." 10 times or "_" .
If someone wants to provide low quality he will be always able to be. 
we could check for at least one letter or digit in the regex but this wouldn't protect us fully. 

proposal : `/^(?=.*[a-zA-Z0-9])(?! *$).{10,1999}$/`

Explanation: 

- Are between 10 and 1999 characters long.
- Do not consist solely of whitespace characters.
- Contain at least one letter or digit.
