### ISSUE TITLE
sig#700 - Add a new csv bulk upload modal to the "My Company" section

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1026]
### Description

In the page `https://portal.int.catena-x.net/companyData` under the section "My Company" 
![image](https://github.com/user-attachments/assets/230224bb-a8f2-46eb-ad4c-77abb457435c)

the user should be able to upload his business partner data in a bulk upload with a provides CSV template. This enables him a quicker onboarding and recudes his effort by uploading every business partner information by hand. 

![image](https://github.com/user-attachments/assets/96eb63b8-f2d0-44c3-8c32-a807e914dbef)

**Valuable Information**
Swagger Docu: https://business-partners.int.catena-x.net/companies/test-company/ui/swagger-ui/index.html#/partner-upload-controller/getPartnerCsvTemplate

Endpoint: `/v6/input/partner-upload-process` 
Method: `GET`

**User Story: Accessing CSV Upload Page**
- As a user, I want to click on the CSV upload button and be redirected to a new `modal` page designated for CSV uploads, so that I can manage my uploads in a dedicated space.
-  As a user i want to have a `modal` with two sections where i can download the csv template in the first section and can reupload it in the second section.
- As a user, I want the system to allow only authorized users (Role: `write_input_partner` ) to upload files, to secure the upload process and protect sensitive data

**User Story: Downloading Blank CSV Template**
- As a user performing my first upload, I want to download a blank CSV template, so that I have the correct format for entering my business partner data.
- As a user i want to receive a new popup where i can define the place to store the new file. 

**User Story: Uploading prepared  CSV Template**
- As a user, i want to have a clear text above the upload button that explains the the preconditions ENG: `To upload your CSV data, the file size must be 1 MB or less.` GER: `Zum Hochladen Ihrer CSV-Daten muss die Dateigröße 1 MB oder weniger betragen.`
- As a user, i want to have an upload button in the second modal where a file-picker opens

**User Story:  Upload limitations**
- As a user, I can only upload CSV files with a maximum file size of 1MB, to ensure quick uploads and prevent system overload.
- As a user, I can upload one file at a time to maintain an organized data upload process and ensure data integrity.
- As a user, the upload selection window should be restricted to only show csv formatted files. 

**Uploading Progress** 
-  As a user i want to have a percentage indicator how much data was processed already after i did press "upload" (progress circle)

### Testcases

Test Case 1: Valid CSV File Upload |   |  
-- | -- | --
Preconditions | Test Steps: | Expected result
Ensure the user is authorised to upload files.Ensure the application is up and running. | Select and Upload File:- Select the file valid_partner_data.csv. Upload the file.- Verify Upload Progress: Monitor the upload progress.Verify Upload Response:- Verify that the file is successfully uploaded and processed without any errors.- The system should return an HTTP status of 200 OK. | 1. The file should be successfully uploaded and processed.2. The user should see the status uploaded successfully.
Test Case 2: Empty CSV File Upload |   |  
Preconditions | Test Steps: | Expected Result
Ensure the user is authorized to upload files.Ensure the application is up and running. | Select and Upload File:- Select the file empty_partner_data.csv.- Upload the file.Verify Upload Progress:- Monitor the upload progress.Verify Upload Response:- Verify that the file is rejected.- The system should return an HTTP status of 400 Bad Request with an appropriate error message indicating that the file is empty. | 1. The file should be rejected with an appropriate error message.
Test Case 3: Non-CSV File Upload |   |  
Preconditions | Test Steps: | Expected Result
Ensure the user is authorized to upload files.Ensure the application is up and running. | Select and Upload File:- Select the file non_csv_partner_data.xls.- Upload the file.Verify Upload Progress:- Monitor the upload progress.Verify Upload Response:- Verify that the file is rejected.- The system should return an HTTP status of 400 Bad Request with an appropriate error message indicating that the file format is not supported.Detailed Error Messages:- Verify that the system provides a detailed error message with row and column information if applicable. | 1. The file should be rejected with an appropriate error message.

### Acceptance Criteria 

- [ ] When the user clicks on the CSV upload button, the system should open a modal window.
- [ ] The modal should be easily closable by the user, either by clicking outside the modal or by providing a close button.
- [ ] The modal should be responsive and adapt to different screen sizes, ensuring a good user experience on both desktop and mobile devices.
- [ ] When the modal is closed, the user should be returned to the previous page or the main application interface.
- [ ] The modal should have a clear and prominent title, such as "CSV Upload".
- [ ] The modal should have a dedicated section for downloading the CSV template.
- [ ] This "download" section should include: A clear label or title, such as "Download CSV Template".
- [ ] This "download" section should include:  A prominent "Download Template" button that allows the user to download a blank CSV template.
- [ ] This "download" section should include:  The downloaded file should be in the correct CSV format, with the necessary column headers or structure.
- [ ]  The modal should have a separate section for uploading the CSV file
- [ ] This "upload" section should include: A clear label or title, such as "Upload CSV File".
- [ ] This "upload" section should include:  A prominent "Choose File" button that allows the user to select a CSV file from their local file system.
- [ ] This "upload" section should include: The file input should only accept CSV file formats, rejecting any other file types.
- [ ] This "upload" section should include:  Once a file is selected, the file name should be displayed in this section.
- [ ] This "upload" section should include:  A "Upload" button that initiates the file upload process when clicked.
- [ ] During the upload i get a clear indication of the stage of the progress via a progress-circle

**Comment by MaximilianHauer** [comment]
Hi @manojava-gk  could you please adjust this screen to put the csv upload button into the same line as the other buttons. 


![Image](https://github.com/user-attachments/assets/0852fbf6-27f9-4f65-bb05-86d79853a9c5)

**Comment by MaximilianHauer** [comment]
![image](https://github.com/user-attachments/assets/7cdae6b4-dac1-4e17-a646-f48a533ab595)
the success message is shown as soon as i press the download button but this doesnt make sense. we should show it as soon as the download happens or we remove it as it confuses people.

**Comment by evegufy** [comment]
@MaximilianHauer I suggest to move to milestone for R24.12 as there are still changes needed

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer
I have checked this user story, and it is working according to the requirements.

Attached Screenshots for References
![image](https://github.com/user-attachments/assets/24a1fc12-21a3-44e8-8e73-661e83e3b9b9)
![image](https://github.com/user-attachments/assets/8fdd9e97-19f2-490e-b619-147fcf2399c9)

**Comment by MaximilianHauer** [comment]
@manojava-gk  is the maximum really 1 mb ?  i assume this could be to low. can we raise it to e.g.5mb ?

**Comment by manojava-gk** [comment]
@MaximilianHauer I'm not sure whether BPDM server supports 5mb or not. Will check with the team and update

**Comment by manojava-gk** [comment]
@MaximilianHauer BPDM supports upto 10mb. We can update this as well
