### ISSUE TITLE
Provide proper error message handling for the technicalUserManagement Page

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1034]
### Description
**As** a User
**WHEN** i receive an error message in the technicalUserManagement page
**THEN** i should receive a clear and understandable error messages that provides me guidance 

**Examples**
- Deletion of a technical user that is still pending 
- Delete a user with an active connector/subscription

### Acceptance Criteria

- [ ] When an error occurs in the backend, the frontend should display the error message provided by the backend.
- [ ] The error message should be displayed in a prominent and accessible location on the user interface, such as a dedicated error section or a modal/popup.
- [ ] The error message should be clear, concise, and easy to understand for the user.

**Comment by MaximilianHauer** [comment]
i did create the ticket before i had a discussion with @oyo  that we should work on an a generic error handling forwarding the error message from the backend into the frontend. created a ticket for this. 

if you can quick fix it i propose to do the ticket if you say it is not worth it we close it. 

error response: 
![image](https://github.com/user-attachments/assets/a99c12c9-cf70-4729-a3c2-b479da1ac9ea)

**Comment by manojava-gk** [comment]
@MaximilianHauer I have already addressed it. @Phil91 gave this updated response. it is available in the PR

**Comment by MaximilianHauer** [comment]
@manojava-gk  if i try to delete a tec user that has an active connector i receive an error message in the console but no where in the frontend :O nothing happens. 
![Image](https://github.com/user-attachments/assets/5e887b89-4903-46e4-8bac-178f1a94ec17)
