### ISSUE TITLE
Not able to download SD document in Connector Management

### ISSUE THREAD

**Issue by lavanya-bmw** [eclipse-tractusx/portal-frontend#1037]
### Current Behavior
On clicking self description document, instead of downloading document, it throws error.
API should be updated for downloading the document

### Expected Behavior
SD document should get downloaded on click of self description document

### Steps To Reproduce
->navigate to Connector Management page and click on details in table 
->If SD document is available, then link will be available which should be clickable
->on click of the SD document, it throws error

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer 
I tested this issue its working fine now.
attached Screenshots for references
<img width="959" alt="image" src="https://github.com/user-attachments/assets/0874b943-5c43-4fde-b407-226b6a451b91">
