### ISSUE TITLE
sig#803 Connector Management - Technical User selection resetting after input fields are updated

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1064]
### Current Behavior

As soon as i select a technical user and then proceed to fill the fields bellow the dropdown above gets cleared 

![image](https://github.com/user-attachments/assets/5c71a6d5-16af-457e-80cf-18d10dae93f1)

### Expected Behavior

* technical user selection should persist not matter if i receive an error in the bellow fields or not. 

### Steps To Reproduce

1. go to https://portal.int.catena-x.net/connectorManagement
2. create a new connector 
3. select a technical user that is existing already
4. select a field bellow and start typing.

**Comment by lavanya-bmw** [comment]
> @lavanya-bmw i assume this should be "in preview" ?

There is another bug in the same overlay, so after working on that, I will move this ticket to review @MaximilianHauer

**Comment by MaximilianHauer** [comment]
@lavanya-bmw please describe the bug shortly in the issue comment that i am aware during testing to have a look :)

**Comment by lavanya-bmw** [comment]
> @lavanya-bmw please describe the bug shortly in the issue comment that i am aware during testing to have a look :)

These are the below bugs which are fixed in https://github.com/eclipse-tractusx/portal-frontend/pull/1119:
-Customer link selection is getting reset after input fields are updated(similar to technical user selection)
-Fields should get reset when navigated to 'connect company connector' overlay

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer 
I checked this bug, and it's working fine now. This issue has been resolved.

attached those screenshots 
![image](https://github.com/user-attachments/assets/1a8f8e26-4460-4c97-bb7d-b906743429d6)
![image](https://github.com/user-attachments/assets/9883d7e5-bce7-49af-b19c-36d11a09daca)
