### ISSUE TITLE
sig#803 - Adjust Delete connector with technical User Popup 

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1065]
### Description
![image](https://github.com/user-attachments/assets/6006e927-afbd-4350-ade7-ff5af232d148)

We would need to adjust the following mask as we enhance the functionality of the connector deletion.
It should be possible to delete the connector without deleting the technical user but we still need to provide the option to delete both. 

#### 1.  Adjust text 

"Please note, the connector has a technical user connected - the technical user can be deleted if you select the checkbox bellow otherwise only the mapping between connector and technical user will be deleted."

#### 2. Adjust Confirm button
Deletion of a connector should be possible without the selection of the checkbox. 
checkbox should not be mandatory for the confirm button

#### 3. Provide parameter to the DELETE API 

If the user checks the checkbox the api should provide the parameter `?deleteServiceAccount=true`
If the user **does not** activate the checkbox the api should provide the parameter `?deleteServiceAccount=false`

### remove deletion button on connectorManagement page 

Button that deletes the connector should be removed on the detail page 

### Acceptance Criteria
- [ ] The text should be updated
- [ ]  Deletion of a connector should be possible without the selection of the checkbox.
- [ ] The checkbox should not be mandatory for the confirm button.
- [ ]  If the user activates the checkbox, the API should provide the parameter `?deleteServiceAccount=true`.
- [ ] If the user does not activate the checkbox, the API should provide the parameter `?deleteServiceAccount=false`.
- [ ] the user is not able to delete the connector from the connectorManagement page anymore 

### Test Cases 

**1. Verify the updated text**
   - Description: Ensure the text "Please note, the connector has a technical user connected - the technical user can be deleted if you select the checkbox bellow otherwise only the mapping between connector and technical user will be deleted." is displayed correctly.
   - Steps:
     1. Navigate to the connector deletion screen.
     2. Observe the text displayed.
   - Expected Behavior:
     - The text should be displayed as expected, providing clear information about the connector deletion process.

**2. Verify connector deletion without checkbox selection**
   - Description: Ensure the user can delete the connector without selecting the checkbox.
   - Steps:
     1. Navigate to the connector deletion screen.
     2. Verify the confirm button is enabled without selecting the checkbox.
     3. Click the confirm button to delete the connector.
   - Expected Behavior:
     - The confirm button should be enabled without the checkbox selection.
     - The connector should be deleted successfully.

**3. Verify connector deletion with checkbox selection**
   - Description: Ensure the user can delete the connector by selecting the checkbox.
   - Steps:
     1. Navigate to the connector deletion screen.
     2. Select the checkbox.
     3. Verify the confirm button is enabled.
     4. Click the confirm button to delete the connector.
   - Expected Behavior:
     - The confirm button should be enabled with the checkbox selection.
     - The connector should be deleted successfully.

**4. Verify the DELETE API parameter when checkbox is selected**
   - Description: Ensure the API call includes the correct parameter when the checkbox is selected.
   - Steps:
     1. Navigate to the connector deletion screen.
     2. Select the checkbox.
     3. Click the confirm button to delete the connector.
     4. Observe the API call made during the deletion process.
   - Expected Behavior:
     - The API call should include the parameter `?deleteServiceAccount=true`.

**5. Verify the DELETE API parameter when checkbox is not selected**
   - Description: Ensure the API call includes the correct parameter when the checkbox is not selected.
   - Steps:
     1. Navigate to the connector deletion screen.
     2. Do not select the checkbox.
     3. Click the confirm button to delete the connector.
     4. Observe the API call made during the deletion process.
   - Expected Behavior:
     - The API call should include the parameter `?deleteServiceAccount=false`.

**6. Verify the user cannot delete the connector from the connectorManagement page**
   - Description: Ensure the user is not able to delete the connector from the connectorManagement page.
   - Steps:
     1. Navigate to the connectorManagement page.
     2. Locate the connector that needs to be deleted.
     3. Attempt to initiate the delete action for the connector.
   - Expected Behavior:
     - The user should not be able to delete the connector from the connectorManagement page.

**Comment by charmi-v** [comment]
Here’s a suggestion regarding the issue highlighted above:

There are currently two types of delete connector pop-ups. The first appears on the Connector Management page, which is the one currently being discussed. The second appears when performing the delete operation from the Connector Details overlay, where a different pop-up is used.

It’s unclear whether having distinct pop-ups for the same operation is necessary. Please confirm if you agree that we should consider consolidating them into a single, unified pop-up (which is being enhanced as part of this issue).

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer 
I have checked this user story, and it is working according to the requirements.

Attached Screenshots for references.
![image](https://github.com/user-attachments/assets/7c51f76c-df78-4fcb-b9c7-9dc000e76970)
<img width="960" alt="image" src="https://github.com/user-attachments/assets/45e7b011-cdbd-4da8-b3e6-d70d5cfd8661">
![image](https://github.com/user-attachments/assets/326fbf53-1031-47a6-a96b-9d0a4dc84839)
