### ISSUE TITLE
Adjust the Title + text of the idpManagement page

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1075]
### Current Behavior

Title and text seems to be temporary and need to be adjusted 

### Expected Behavior

![image](https://github.com/user-attachments/assets/8ed4ddc0-f766-45bc-a5d0-6cb3ddae8c81)

Title: "Identity Provider configuration" 
Text: 

> This page provides the functionality to manage user authentication for your company.
> 
> Upon registration, we have established an Identity Provider (IDP) with a single user entry for the administrator. Many organizations already maintain their own IDP, where users authenticate using their established company user IDs and familiar login interfaces. In such cases, you may prefer to leverage your existing company IDP. You can create and manage the necessary federation on this page.

### Steps To Reproduce
* Open the page https://portal.int.catena-x.net/idpManagement 
* read the title + text above the picture.

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
I tested this issue it's working fine. Can you close this ticket.

Attached Screenshot for references:
![image](https://github.com/user-attachments/assets/ab9c22cf-147e-4f56-9034-940d44809b13)
![image](https://github.com/user-attachments/assets/8caafb0f-686f-4993-8a6c-c8bb8db54e7c)
