### ISSUE TITLE
sig#789 - Enhance technicalUserManagement creation page by type + serviceurl

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1077]
### Description:
As a Frontend Developer, I need to update the technical user self-service creation UI to include:

* fields for technical user type 
* fields for service endpoint so that operators can specify and view this information during user setup.
* clear separation of internal / external users 
* logic adjustment to ensure that the simultaneous selection of internal users and external users is not possible

precondition
* https://github.com/eclipse-tractusx/portal-backend/issues/976
* https://github.com/eclipse-tractusx/portal-backend/issues/977

#### Internal User Section

- [ ] The system should have a dedicated section for internal users.
- [ ] The internal user section should allow the selection of multiple internal users using a checkbox interface.
- [ ] The selection of an external user should automatically disable the selection of the internal user.

#### External User Section

- [ ] The system should have a dedicated section for external users.
- [ ] The selection of an internal user should automatically disable the selection of the external user.

#### Technical User Roles

- [ ] A technical user can have only one external role, which should be selected using a radio button interface.
- [ ] The UI should have appropriate controls for viewing technical user types.

#### Additional Description

- [ ] The system should include a description explaining that the selection of internal and external users for the same service is not possible.
- [ ] If an external user is required for a service, the description should advise the user to create the external user separately.

#### Documentation 
- [ ] The Documentation in https://github.com/eclipse-tractusx/portal-assets/tree/main/docs/user/03.%20User%20Management/03.%20Technical%20User should be updated accordingly

**Comment by lavanya-bmw** [comment]
@MaximilianHauer once BE changes are available, I will proceed with this ticket

**Comment by MaximilianHauer** [comment]
@lavanya-bmw  you can work on this. can you tell me that blocks you ?

**Comment by lavanya-bmw** [comment]
> @lavanya-bmw you can work on this. can you tell me that blocks you ?
I'm working on this Max

**Comment by MaximilianHauer** [comment]
@manojava-gk  / @lavanya-bmw / @oyo 

we should align on how to implement this logic "clear separation of internal / external users"
proposal would be like this , please provide me feedback if you see issues regarding logic/implementation 

![Image](https://github.com/user-attachments/assets/41ef1f34-b5f3-4f02-afa6-c47ece211333)

**Comment by manojava-gk** [comment]
@MaximilianHauer I like this approach. I do not see any problem to implement also.

**Comment by MaximilianHauer** [comment]
Hi @cofinity-ux 

do you have a proposal for us how we should design this ? currently we would just place some greyish border around the internal & external sections.

**Comment by MaximilianHauer** [comment]
@lavanya-bmw  i raised the story point count based on the feedback from sarah. 
i really like the idea to separate internal external with radio buttons as it is right that the user would end up in a lock if he missclicks. 

the description should be bellow the radio buttons in the same format as we du it for the technical user. 

**Internal technical user** 
_Internal technical user are created in the direct environment of the portal therefor can have multiple roles_

**External technical user** 
_External technical user are created in external environment therefor can only have one role_

**Comment by MaximilianHauer** [comment]
tested works
