### ISSUE TITLE
OSP Registration | Unable to submit the Company Registration 400 error

### ISSUE THREAD

**Issue by JordanGerada3** [eclipse-tractusx/portal-frontend#1079]
### Current Behaviour

Despite selecting all company roles and accepting the terms and conditions, a 400 error is still being thrown because the system is not actually registering the updated selection of the terms and conditions.

### Expected Behavior

Ideally, system allows to submit the registration details with pre-selected & new/updated ones Company role(s).

### Steps To Reproduce

- Register a Company  via OSP
- Configure everything for authentication → Redirect URI (Azure)
- Login via ENRTY portal --> search for that invited company
- Login to invited company
- Check/select all T&C
- Hit Submit

<img width="1267" alt="Screenshot_1024" src="https://github.com/user-attachments/assets/8079a400-a107-42a9-879b-8e0798004c4a">

**Comment by MaximilianHauer** [comment]
@JordanGerada3  is this not needed anymore ? please ensure to close the related PR too then. 
we have a closed issue but a PR in draft this causes confusion :)

**Comment by JordanGerada3** [comment]
> @JordanGerada3 is this not needed anymore ? please ensure to close the related PR too then. we have a closed issue but a PR in draft this causes confusion :)

This shouldn't have been closed, I'm not entirely sure how that happened but I've reopened. It's still in regards to the draft PR you mentioned.

**Comment by MaximilianHauer** [comment]
updates the status properly
