### ISSUE TITLE
sig#789 - Enhance the Technical User Overview with UserType Column

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1082]
### Description

The overview of the technicalUserManagement page needs to be enhanced to provide more clarity. 

* Add a new column called "Usertype" this should present the value `usertype` from the endpoint `GET: api/administration/serviceaccount/owncompany/serviceaccounts` 
* Rename the column Type to "Ownership" 

precondition: 
* https://github.com/eclipse-tractusx/portal-backend/issues/976

### Acceptance Criteria

- [ ] The "Usertype" column is added to the technicalUserManagement page, displaying the usertype value from the GET: api/administration/serviceaccount/owncompany/serviceaccounts endpoint.
- [ ] The existing "Type" column is renamed to "Ownership".
- [ ] The layout and formatting of the page is updated to accommodate the new column and column name change.
- [ ] The page should load and display the updated information without any errors or performance issues.
- [ ] The Documentation in https://github.com/eclipse-tractusx/portal-assets/tree/main/docs/user/03.%20User%20Management/03.%20Technical%20User should be updated accordingly 

#### Verify the "Usertype" column is added
**Steps:**
Navigate to the technicalUserManagement page.
Verify that a new column named "Usertype" is present.
**Expected Result:** The "Usertype" column is displayed on the page.

#### Verify the "Usertype" column displays the correct data
**Steps:** Make a request to the GET: api/administration/serviceaccount/owncompany/serviceaccounts endpoint.
Verify that the "Usertype" column on the technicalUserManagement page displays the correct usertype value for each row.
**Expected Result:** The "Usertype" column displays the correct usertype value for each service account.

#### Verify the "Type" column is renamed to "Ownership"
**Steps:**
Navigate to the technicalUserManagement page.
Verify that the "Type" column is renamed to "Ownership".
**Expected Result:** The "Type" column is renamed to "Ownership".

#### Verify the page layout and formatting
**Steps:**
Navigate to the technicalUserManagement page.
Verify that the layout and formatting of the page is updated to accommodate the new "Usertype" column and the renamed "Ownership" column.
Verify that the page loads and displays the information without any visual issues or performance problems.
**Expected Result:** The page layout and formatting are updated correctly, and the page loads and displays the information without any issues.

#### Verify error handling and edge cases
**Steps:**
Simulate errors or edge cases, such as:
Failure to fetch data from the GET: api/administration/serviceaccount/owncompany/serviceaccounts endpoint.
Unexpected data format or structure from the endpoint.
Verify that the page handles these scenarios gracefully and displays appropriate error messages or fallback content.
Verify that the page remains functional and does not crash or exhibit unexpected behavior when encountering these errors.
Expected Result: The page should handle errors and edge cases gracefully, displaying appropriate error messages or fallback content, and maintain its overall functionality.

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer 
I checked this bug, and it's working fine now. This issue has been resolved.

Attached Screenshots for references
![image](https://github.com/user-attachments/assets/a3c07e15-007f-4fa4-ba9a-692e78a8484b)
![image](https://github.com/user-attachments/assets/e07d9016-2aab-4aff-945c-9ce70892c74a)
![image](https://github.com/user-attachments/assets/507a16dd-9c9d-4827-85f2-1b86a5eeb216)
