### ISSUE TITLE
Frequent Auto refresh/reload pages disrupts the Ongoing process

### ISSUE THREAD

**Issue by SanaSalem01** [eclipse-tractusx/portal-frontend#1094]
Currently, this is very disrupting when user is in the middle of Onboarding app, service etc then the auto-refresh call resets the data to none if its not saved. 

PLEASE NOTE: This is happening across the whole system.

**Steps to Reproduce:**

- Login to the Entry portal as CX-operator
- Onboard/Register a new app (App management ---> App Release process--> Register App)
- Add required input data
- Switch to other tabs for 1 minute or so
- Switch back to App registration tab

**Current/Actual behavior:**
The system auto-refresh/load which makes user to navigate back to App Overview screen to resume the App registration. (This is very annoying for the user as the system gets refresh and then navigate back etc)

**Comment by evegufy** [comment]
Hi @SanaCofinityX just saw you issue and we investigated this issue in the past and I link the summary https://github.com/eclipse-tractusx/portal-iam/blob/v3.0.1/docs/consultation/workshop-20231005.md

**Comment by MaximilianHauer** [comment]
@SanaSalem01  i assume we can close this issue ?

**Comment by SanaSalem01** [comment]
@MaximilianHauer Yes, we can close it.
