### ISSUE TITLE
fix: Tag Section in App Management > App Overview Need to remove

### ISSUE THREAD

**Issue by Usmanfee** [eclipse-tractusx/portal-frontend#1121]
### Current Behavior
The Tag section in the App overview page needs to be removed because there is no functional need to display it. While creating the app through the wizard steps, we don't have any information regarding the mentioning of tags and their related information on any screen. The same tag also exists in the navigation of the app overview, which also needs to be removed.

### Expected Behavior
App overview page should not have any section named as "**Tags**".

### Steps To Reproduce

- Navigate to the "App Management" | “App Overview“ section.
- Open an app details page.
- Observe the title displayed as 'Tags' at the bottom of the page.

**Comment by typecastcloud** [comment]
Please enhance title and description. The issue is really hard to understand for me. The tag system seems to be abandoned but maybe the correct fix for upstream is finishing the tag system.
Also not sure if this counts as a bug or enhancement.

**Comment by MaximilianHauer** [comment]
furthermore please provide proper testcases and acceptance criteria to raise the quality of the request. 
personally i am a big fan of screenshots as it eases up the understanding without iterating through the app ;)

**Comment by ybidois** [comment]
> overall the whole app user journey is not finished yet and needs to be enhanced still. doesnt make sense to remove sections now as "bug"

Hi Max, we could think in the future of using feature flags for features that are still in progress? So we can hide them until they're finished. 

App managers will look how use the tags and not find it, just as we did, hence our belief it was a bug and our attempt to hide them. 

But you're right, this is not a bug!

**Comment by typecastcloud** [comment]
Adding some kind of feature flags system might be a good idea in general. Or at least the option to use/enable one.

**Comment by MaximilianHauer** [comment]
@ybidois  valid point. ill pick it up and take it with me but would start implementing it with new functionality that is not in place yet otherwise we are just blocking/confusing ourselves.
