### ISSUE TITLE
Technical Role description is displayed weird on small screens 

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1146]
### Current Behavior

If i open `https://portal.int.catena-x.net/technicalUserManagement` and create a new technical user in a reduced window size the description is overlapping 
![image](https://github.com/user-attachments/assets/47061542-1a70-4238-903a-6a997092c607)

### Expected Behavior

the page should be responsive and the text should break in a new line and not overlap 

### Steps To Reproduce

1. Open https://portal.int.catena-x.net/technicalUserManagement`
2. press "Create Technical User"
3. resize the window

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer 
i tested this issue. it's working fine.

attached screenshots for references:
![image](https://github.com/user-attachments/assets/8564113e-bca7-4cf0-af5d-c87f0e1a1ed4)
