### ISSUE TITLE
URL Navigation fails when clicking on the Apps in Home Page.

### ISSUE THREAD

**Issue by gopalreddy-bmw** [eclipse-tractusx/portal-frontend#1147]
**Current Behaviour**
Clicking on apps in Home page URL Navigation failed.

**Screenshot**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/abfc2d3d-80c0-4302-9593-73c80bc7f911">

**Expected Behaviour**
Clicking on Apps in Home page should be navigate particular App URL.

**Screenshot**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/4aef15ce-9402-47d7-8733-50e46bcaf643">

**Steps To Reproduce**
1.Login to Catena-X Portal.
2.Click on Home Button
3.drag to the bottom of the page
4.Clicking on Apps and Observe

**Comment by MaximilianHauer** [comment]
you did use egde right ? i use chrome and it does not seem to be clickable. valid finding !

**Comment by gopalreddy-bmw** [comment]
Chrome also clickable but url navigation fail both edge and chrome browser.

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
i Tested this issue it's working fine. Can you close this ticket.

Attached Screenshots for references
![image](https://github.com/user-attachments/assets/ea190846-ec0a-4879-85a2-581f4f24ba45)
![image](https://github.com/user-attachments/assets/f4ce67d4-dfc1-4a58-9f09-57b4ed3e0e26)
![image](https://github.com/user-attachments/assets/699026c3-8076-4cd5-805e-6ce7d0695dcf)
