### ISSUE TITLE
Data Space Page Manage UseCase Credentials URL is incorrect

### ISSUE THREAD

**Issue by gopalreddy-bmw** [eclipse-tractusx/portal-frontend#1152]
**Current Behaviour**
https://portal.int.catena-x.net/usecase-participation
This URL is incorrect

**Expected Behaviour**
https://portal.int.catena-x.net/usecaseParticipation
 This URL is correct

**Steps To Reproduce**
1.Login to the Catena-X Portal
2. Clicking on Data Space Page
3. Drag to end of the page
4. Click on Manage usecase Credentials

Note: columns are not align correctly also meaning of short category in unclear
**Screenshot**
![image](https://github.com/user-attachments/assets/e5179c2f-5a21-4ade-a012-cc54ffc21117)

**Comment by kunalgaurav-bmw** [comment]
As per my finding the url end value and short category getting from API need to change from backend.
