### ISSUE TITLE
Technical user Management Table Column Header Sort Option is overlapped with Header.

### ISSUE THREAD

**Issue by gopalreddy-bmw** [eclipse-tractusx/portal-frontend#1158]
**Current Behaviour**
Mouseover to Column header sort option is overlapped with header.
**Screenshot**
<img width="958" alt="2024_09_26_19_07_22_" src="https://github.com/user-attachments/assets/657917eb-69b6-42af-abc6-d982e85afd30">

**Expected Behaviour**
sort option should not overlapped with Column Header.

**Screenshot**
<img width="960" alt="2024_09_26_19_12_35_" src="https://github.com/user-attachments/assets/8c5c244f-1468-4ac4-b40b-58428439c93d">

**Steps To Reproduce**
1.Login to the Catena-X Portal
2.Mouseover to Company Roles
3.Clicking on Participant
4.Drag to User Management Header
5.Click on User Management
6.Click on technical user Management
7.Mouseover to column header and observe.

**Comment by MaximilianHauer** [comment]
@gopalreddy-bmw  i think you can retest this

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
i tested this issue it's working fine. Can you close this issue

attached screenshots for references 
<img width="955" alt="image" src="https://github.com/user-attachments/assets/295cf067-74f9-46e6-bf6d-ffc19012526e">
