### ISSUE TITLE
Notification Translations Needs to be Harmonised with Constants

### ISSUE THREAD

**Issue by Usmanfee** [eclipse-tractusx/portal-frontend#1163]
### Current Behavior
Currently, we have a naming convention conflict between the keys mentioned in the Notification Translation and the keys in the constants file. In the code, we are mapping constant keys to translations to retrieve the relevant translation. However, due to mismatched word casing, it results in the translation key being returned instead of the value.

<img width="1135" alt="Screenshot 2024-09-27 at 08 57 04" src="https://github.com/user-attachments/assets/f8ba3a2a-6e9d-4e33-960f-d96e4e485f2b">
<img width="1114" alt="Screenshot 2024-09-27 at 08 58 51" src="https://github.com/user-attachments/assets/52b093d0-cc58-4969-a2f4-7f40f0e4a185">
<img width="1064" alt="Screenshot 2024-09-27 at 09 00 59" src="https://github.com/user-attachments/assets/2d078a93-1c55-4ccb-819d-b2227f2a6bcb">

![Screenshot 2024-09-27 at 09 57 20](https://github.com/user-attachments/assets/89eea85a-29a9-4f0a-a8b4-db708d20846b)

### Expected Behavior
The keys format(either camelcase, or any other) used in Notification translation file should be consistent with the key's value in CONSTANT.ts. 

### Steps To Reproduce

- Navigate to Profile Menu to top right.
- Select Notification option from menu.
- Open notification card and observe the link of the text.

**Comment by oyo** [comment]
@MaximilianHauer Checked with @gopalreddy-bmw - there was no test data available but we checked and confirmed it's implemented in the code.
