### ISSUE TITLE
App Subscription Page Read more link is Not clickable 

### ISSUE THREAD

**Issue by gopalreddy-bmw** [eclipse-tractusx/portal-frontend#1170]
**Current Behaviour**
Read more link is not clickable in App Subscription page

**Screenshot**
![image](https://github.com/user-attachments/assets/68bf3272-b7eb-4a99-8a7a-0031cacf75b1)

**Expected Behaviour**
Read more link is should be  clickable in App Subscription page

**Steps To Reproduce**
1.Login to the Catena-X Portal
2.Mouseover to Company Roles
3.Clicking on App Provider
4.drag to App Subscription Process click on Subscription Management Board
5.Click on Read more and observe

**Comment by MaximilianHauer** [comment]
@lavanya-bmw  please use the following page https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/user/04.%20App(s)/05.%20App%20Subscription/03.%20Subscription%20Overview%20(App%20Provider).md

**Comment by lavanya-bmw** [comment]
> @lavanya-bmw please use the following page https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/user/04.%20App(s)/05.%20App%20Subscription/03.%20Subscription%20Overview%20(App%20Provider).md

@MaximilianHauer As we are using documentation links, I used the below link https://portal.int.catena-x.net/documentation/?path=user%2F04.+App%28s%29%2F05.+App+Subscription%2F03.+Subscription+Overview+%28App+Provider%29.md
