### ISSUE TITLE
IDP Management page Action disable status is not updated

### ISSUE THREAD

**Issue by gopalreddy-bmw** [eclipse-tractusx/portal-frontend#1182]
**Current Behaviour**
IDP Management page Action disable status is not updated

**Screenshot**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/8ede4760-d135-4bb4-afea-f21aa8ba92cc">

**Expected Behaviour**
IDP Management page Action disable status should be updated.

**Screenshot**
<img width="960" alt="image" src="https://github.com/user-attachments/assets/d4fcaf19-b8f1-4c30-8275-9008077986b5">

**Steps To Reproduce**
1.Login to Catena-X Portal
2.Click on User Menu
3.Click on Onboarding Service Provider
4.Click on Actions opens and enable and observe

**Comment by lavanya-bmw** [comment]
The fix for this issue is available in https://github.com/eclipse-tractusx/portal-frontend/pull/1132

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
i Tested this issue it's working fine. Can you close this ticket

Attached Screenshots for references 
![image](https://github.com/user-attachments/assets/2506e6e4-f5b3-42f5-b685-e7021f84a60c)
![image](https://github.com/user-attachments/assets/093d654b-d1bb-43d8-b2e8-878f3290b8ef)
