### ISSUE TITLE
App | Service subscription searchbox translation

### ISSUE THREAD

**Issue by Usmanfee** [eclipse-tractusx/portal-frontend#1210]
### Current Behavior
The translations are not available in DE for search as placeholder text in both App and Service subscription UI.

### Expected Behavior
The search should display correct translation for the selected language either in DE or in EN.

### Steps To Reproduce

- Navigation to the `App SubscriptionManagement` from `App Management`.
- observe the placeholder text for the searchbox.
- change the language from en to de.
- observe no change in translations for placeholder text.

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
I tested This issue it's working fine. Can you close this ticket.

Attached Screenshots for references:
![image](https://github.com/user-attachments/assets/ab1fa620-3875-4cc1-89c4-12d58b127233)
![image](https://github.com/user-attachments/assets/680a406b-6e09-4817-b3ee-79651627759e)
![image](https://github.com/user-attachments/assets/60476529-4077-44b9-bbe2-9520ce610a95)
![image](https://github.com/user-attachments/assets/a9e12ef7-da90-4432-87f5-633e73cce66c)
