### ISSUE TITLE
Details of an App do not show the attached documents 

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1227]
### Current Behavior
* If i go into the details page of an app the documents are not shown.

### Expected Behavior

* if documents are uploaded for an app the respective documents should be shown in the frontend and should be downloadable 

### Steps To Reproduce

1. open the app overview 
2. select the details of an app
3. scroll to the download section 
![image](https://github.com/user-attachments/assets/9e00da6e-76f1-4dff-ac52-e95a50cce3cd)

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
I tested this issue it's working fine. Can you close this issue.

Attached screenshots for references 
![image](https://github.com/user-attachments/assets/cb98943d-e659-48b1-93bc-2d1f205faa5e)
