### ISSUE TITLE
sig#809 - OSP | Customer Overview | Blank page and TypeError

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-frontend#1228]
### Current Behavior

Blank page and TypeError in Customer Overview Tab of OnboardingServiceProvider Page

### Expected Behavior

No Blank page and TypeError in Customer Overview Tab of OnboardingServiceProvider Page

### Steps To Reproduce

1. Go to OnboardingServiceProvider Page
2. Switch to Customer Overview Tab

**Comment by evegufy** [comment]
cc: @MaximilianHauer

**Comment by MaximilianHauer** [comment]
i assume we talk about the page /ManagementOnboardingServiceProvider as /onboardingServiceProvider is a different one.

**Comment by lavanya-bmw** [comment]
@evegufy @MaximilianHauer This issue is already addressed in PR https://github.com/eclipse-tractusx/portal-frontend/pull/1132
