### ISSUE TITLE
Remove deprecated page onboardingServiceProvider

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1236]
### Description
The following page was  created as a first draft in the past but is not needed anymore 
https://portal.int.catena-x.net/onboardingServiceProvider
please delete this page 

### Acceptance Criteria

- [ ] onboardingServiceProvider and every related link is removed 
- [ ] if links are found they are replaced/adjusted with ManagementOnboardingServiceProvider

**Comment by MaximilianHauer** [comment]
@oyo  fyi

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
i tested this issue it's working fine. Can you close this issue.

Attached Screenshots for reference.
![image](https://github.com/user-attachments/assets/ab7c3ba3-4032-44b2-b8f0-a25a05a63537)
