### ISSUE TITLE
Enhance appSubscription page (Sectiontitle + adjust filter show all)

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1245]
### Description

As a App provider i would like to have a better understanding on the features i get offered on `https://portal.int.catena-x.net/appSubscription`

for this i would like to have 

1. clear description of the functionality 
2. i want to see also the inactive subscription's if i filter for "show all" 

![image](https://github.com/user-attachments/assets/53bbed4d-fc16-42ff-82d9-fd395b5cb604)

### Acceptance Criteria

- [ ] i want to have a section description above the own app filter "Apps offered"
- [ ] i want to have a section description above the own app filter "Subscriptions"
- [ ] if i filter for "show all" i can see all the subscriptions no matter the status

**Comment by MaximilianHauer** [comment]
@gopalreddy-bmw  i had a longer discussion with mano today and based on this one we aligned to adjust the page like this.

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
I tested this US it's working fine. Can you close this Ticket.

Attached Screenshots for references
![image](https://github.com/user-attachments/assets/9c52dde8-fe68-4caa-9af6-f26b1d4d2d7c)
![image](https://github.com/user-attachments/assets/cdfad12e-2f23-4cba-98a1-e61c4c5a7e15)
