### ISSUE TITLE
Technical User Management | not displaying usertype column data

### ISSUE THREAD

**Issue by lavanya-bmw** [eclipse-tractusx/portal-frontend#1252]
### Current Behavior
The usertype column is not displaying data from API in technical user management

### Expected Behavior
The usertype column should display API data in technical user management page

### Steps To Reproduce
1. Navigate to /technicalUserManagement
2. Check the column usertype, it has data from API response(but not displayed in UI)

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer 
i tested this issue it's working fine. Can you close this issue.

Attached Screenshots for references:
![image](https://github.com/user-attachments/assets/ed4bcd4b-9e32-4113-b1ed-dc9ed68893ee)
![image](https://github.com/user-attachments/assets/958e8188-9b2e-4d35-8b8e-e15e2a21a992)
