### ISSUE TITLE
Responsiveness - maximum screen width needed for all elements (ext: CPLP-2893)

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/portal-frontend#127]
Maximum screen width needed for all elements

 

Positive Example - Microsoft Page:

[image-2023-06-20-11-55-53-138.png](https://github.com/catenax-ng/product-portal-tools/blob/main/jira-import-files/image-2023-06-20-11-55-53-138.png)

 

 

Negative Example - CX Portal:

 

[image-2023-06-20-11-56-31-153.png](https://github.com/catenax-ng/product-portal-tools/blob/main/jira-import-files/image-2023-06-20-11-56-31-153.png)

 

 

_Components_: N/A
_Sprints_: N/A
_Fix Versions_: N/A
_StoryPoints_:N/A
_Attachments_:N/A

**Comment by jjeroch** [comment]
Done
