### ISSUE TITLE
Improve Fielddescription of "Connector Catalog Endpoint"  in /connectorManagement

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#1297]
### Description
Currently the description does not seem to be good enough as the users do not always implement the catalog url but the edc url only. 
this results in faulty data pulled by the discovery service.

1.) adjust the Infobutton to show the following text "Base URL of the [Catalog Service](https://docs.internationaldataspaces.org/ids-knowledgebase/v/dataspace-protocol/catalog/catalog.binding.https#id-2.1-prerequisites) endpoint of a DSP Connector, e.g., [https://connector.control.plane/{catalogPath}](https://connector.control.plane/%7BcatalogPath%7D)." 
2.) rename the field description from "Connector URL" to "Example: https://connector.control.plane/api/v1/dsp"

![image](https://github.com/user-attachments/assets/45ea9e2f-abfd-4548-9827-86711ce5fb4f)

### Acceptance Criteria

- [ ] The Infobutton next to the "Connector URL" field should display the following text:   "Base URL of the [Catalog Service](https://docs.internationaldataspaces.org/ids-knowledgebase/v/dataspace-protocol/catalog/catalog.binding.https#id-2.1-prerequisites) endpoint of a DSP Connector, e.g., [https://connector.control.plane/{catalogPath}](https://connector.control.plane/%7BcatalogPath%7D)."
- [ ]  The field description for the "Connector URL" field should be renamed to "Example: https://connector.control.plane/api/v1/dsp".

**Comment by MaximilianHauer** [comment]
@markuskeidl / @gerbigf provide me please a "helptext" that would provide a better understanding from your point of view.

**Comment by markuskeidl** [comment]
I would recommend the following:

- to change the field description from "Connector URL" to an actual example, e.g., https://connector.control.plane/api/v1/dsp
- to change the info button to something like "Base URL of the [catalog service](https://docs.internationaldataspaces.org/ids-knowledgebase/v/dataspace-protocol/catalog/catalog.binding.https#id-2.1-prerequisites) endpoint of a DSP Connector, e.g., https://connector.control.plane/{catalogPath}."
- (prio 2) do add a check - at least when entering the URL - that this URL actually works, i.e., that a catalog can be fetched from this URL.

**Comment by MaximilianHauer** [comment]
@ntruchsess /  @Phil91 do you have an **efficient** proposal to check if a connector url is accessible ?

**Comment by oyo** [comment]
> @ntruchsess / @Phil91 / @oyo / @evegufy do you have an **efficient** proposal to check if a connector url is accessible ?

@MaximilianHauer from frontend side we are quite limited because of CORS restrictions. Only some basic network checks if SOMETHING is running at the Server https port would be possible.

**Comment by MaximilianHauer** [comment]
ok does not sound like a huge  benefit then we focus on the easy stuff first.
