### ISSUE TITLE
Filters are Not Functioning as Expected 

### ISSUE THREAD

**Issue by gopalreddy-bmw** [eclipse-tractusx/portal-frontend#1317]
**Current Behaviour**
Filters are not Updating  Switch Between Tabs 

**Screenshot**
![image](https://github.com/user-attachments/assets/f2f000be-03b2-4ba8-ac92-6a1a67bfbe69)

**Expected Behaviour**
Filters Should be Update Switching between tabs

**Screenshot**
![image](https://github.com/user-attachments/assets/f381ca96-6275-44d7-9ebb-e8e9ecc17baa)

**Steps To Reproduce**
1. Navigate to https://portal.int.catena-x.net/appSubscription
2. Select the Offers Filters.
3. Switching the offers filter and Observe.

**Comment by lavanya-bmw** [comment]
@MaximilianHauer Not a valid bug, filters are working fine in app subscription.

**Comment by MaximilianHauer** [comment]
@gopalreddy-bmw  for me it works too :O
