### ISSUE TITLE
URL Navigation fails when clicking on Manage use case Credentials in DataSpace Tab 

### ISSUE THREAD

**Issue by gopalreddy-bmw** [eclipse-tractusx/portal-frontend#1336]
**Current Behaviour**
URL Navigation fails when clicking on Manage use case Credentials in Dataspace Tab 

**Screenshot**
![image](https://github.com/user-attachments/assets/4b0c1348-3056-4315-aa3b-f852335cf9b7)

 **Expected Behaviours**
URL Navigation should not fail when clicking on Manage use case Credentials in Dataspace Tab 

**Steps To Reproduce**
1.Login to https://portal.int.catena-x.net/dataSpace
2.Click on Manage use case Credentials

**Comment by evegufy** [comment]
@gopalreddy-bmw this is fixed, you might need to clear your cache, I fixed it with https://github.com/eclipse-tractusx/portal-assets/pull/425

**Comment by gopalreddy-bmw** [comment]
@evegufy it's working fine. Can you close this issue

**Screenshot:**
![image](https://github.com/user-attachments/assets/3e8fb629-2dff-4fc6-8d13-bc2900ad54f9)
