### ISSUE TITLE
IdP config | Don't provide option to configure SHARED IdP

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-frontend#1350]
### Current Behavior

<img width="799" alt="image" src="https://github.com/user-attachments/assets/b5a11388-39e7-4a98-935c-69af8e9060fb">

### Expected Behavior

for Identity Provider with identityProviderTypeId SHARED the configure option and the according overlay should be displayed because the SHARED IdP can't be configured.

the user shouldn't be shown a option that's not viable

### Steps To Reproduce

Detected in v2.3.0-RC4

**Comment by gopalreddy-bmw** [comment]
Hi @MaximilianHauer @evegufy 
i tested this issue it's working fine. Can you close this issue.

Attached screenshots for references
![image](https://github.com/user-attachments/assets/e5095f54-7e8a-4202-8b34-00845496926b)
