### ISSUE TITLE
Can't create Company Data as Cx Admin

### ISSUE THREAD

**Issue by nicoprow** [eclipse-tractusx/portal-frontend#1353]
### Current Behavior

When logged in as Cx Admin of a participating company, I can't create sites or addresses over the Company Data page. Everytime I press the button to confirm the creation I receive an error message instead.

In the network console I can see it is an 403.

The token has no roles for BPDM Gate access (write_input_partner for example)

### Expected Behavior

I can create an address or site without error and the site or address is then listed in the company data.

The token contains all roles to access BPDM Gate as listed here https://github.com/eclipse-tractusx/portal-iam/blob/main/docs/admin/technical-documentation/06.%20Roles%20%26%20Rights%20Concept.md#256-bpdm-gate

### Steps To Reproduce

1. Log in as Cx Admin
2. Navigate to the Company Data page
3. Click Add Site
4. Fill out dialog with valid information
5. Click confirm

<img width="922" alt="grafik" src="https://github.com/user-attachments/assets/481599fc-f749-4ed3-a950-0692fed2350c">
<img width="1037" alt="grafik" src="https://github.com/user-attachments/assets/9fbc6ebf-dd9f-46ef-ae60-402eae117ded">

**Comment by evegufy** [comment]
@nicoprow could you please take this table https://github.com/eclipse-tractusx/portal-iam/blob/v4.0.0-rc.1/docs/technical%20documentation/06.%20Roles%20%26%20Rights%20Concept.md#256-bpdm-gate as basis and provide the information how the role assignment should be adjusted?

**Comment by evegufy** [comment]
@manojava-gk could you please provide the information with which roles you tested this functionality on INT?

**Comment by manojava-gk** [comment]
@evegufy  my test user has following roles

```
"roles": [
        "write_sharing_state",
        "read_sharing_state",
        "read_output_partner",
        "read_stats",
        "read_output_changelog",
        "read_input_changelog",
        "write_input_partner",
        "read_input_partner"
      ]
      ```

**Comment by evegufy** [comment]
got the feedback from @nicoprow that it was successfully retested --> close
