### ISSUE TITLE
QG4: TRG 7.02 - License and Copyright header

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/portal-frontend#218]
Hi @evegufy, issue related to Copyright headers for certain files, below result of the check:

    Testing Quality Guideline: TRG 7.02 - License and Copyright header
    
    Failed! Guideline description: Where possible, all source code should contain appropriate copyright and license notices as well as information on each contribution. 

	Can't find copyright headers at:

	.tractusx
	src/@types/i18next.d.ts
	src/@types/react-slick.d.ts
	src/components/overlays/IDPDelete/idpdelete.scss
	src/components/overlays/IDPDelete/index.tsx
	src/components/overlays/IDPStatusChange/index.tsx
	src/components/overlays/IDPTestRun/index.tsx
	src/components/overlays/IDPTestRun/style.scss
	src/components/overlays/UpdateCompanyRole/style.scss
	src/components/pages/Home/components/StageSection/stage-section.scss
	src/components/pages/UserManagement/StageSection/stage-section.scss
	src/components/shared/basic/CertificateCard/style.scss
	src/components/shared/basic/ReleaseProcess/components/ComponentStyles.scss
	src/components/shared/basic/UserRoles/UserRole.scss
	src/utils/downloadUtils.ts

	More infos: https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-02

**Comment by evegufy** [comment]
License and Copyright header were added.
