### ISSUE TITLE
TRG 4.01 multiple container tags

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/portal-frontend#381]
https://github.com/eclipse-tractusx/portal-frontend/blob/0feb9925d0e34cc2738ccda1c931ab896318710c/.github/workflows/release.yml#L93-L100

release.yaml workflow doesn't create expected multiple container tags, like
- x
- x.y
- x.y.z

Instead, only x.y.z + latest tags will be created: https://hub.docker.com/r/tractusx/portal-frontend/tags?page=1&name=v1

**Comment by evegufy** [comment]
@carslen Thanks for hint! we'll look into multiple container tags as an improvement for the release workflows for the next release. Please annotate that accordingly in https://github.com/eclipse-tractusx/portal-frontend/issues/380.
As semantic versioning as well as tagging is in place, I'd suggest to rename the issue to 'TRG 4.01 multiple container tags'.

**Comment by carslen** [comment]
Multiple container tags will be implemented for next release (24.03).
