### ISSUE TITLE
IdP config - Users | enriched csv results empty after upload

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-frontend#440]
Detected in version:  **1.8.0-RC2**

### Expected behaviour

When downloading the current user list of an  identity provider as csv, enriching the csv and uploading it, the enriched user list is uploaded.

### Current behaviour

Upload of user list results in empty preview (only header of the file is shown) and when confirming the upload an empty file is sent to the backend.

**Comment by jjeroch** [comment]
Reference image:
<img width="659" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/8b342e0d-9db5-4d98-b762-9804d2fa77ae">

**Comment by jjeroch** [comment]
@nidhigarg-bmw  while fixing the bug - can you please also adjust the overlay headline. This has nothing to do with use cases :D we should name it "Update/Migrate User Accounts" please
