### ISSUE TITLE
Company Certificates View Business Partners

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#458]
### Summary
----
Enhance the current "View BP Detail" Screen by adding certificates inside the overlay section

[CPLP-3664-image-2024-01-17-07-03-38-413.png](https://jira.catena-x.net/secure/attachment/23623/image-2024-01-17-07-03-38-413.png)

### Details
----
Figma: {color:#4c9aff}not yet existing{color}

 

- [ ] Enhance the overlay by adding a new section "Company Certificates"

- [ ] Call endpoint GET /api/administration/companydata/\{businessPartnerNumber}/companyCertificates (CPLP-3679)
  * response empty => certificate section should be empty
  * response send, display for each certificate a certificate icon

- [ ] Certificate icon function
 * react on hover
 * clickable
 * has a title/name (certificateType)

 

 

As-Is

[CPLP-3664-image-2024-01-17-07-04-45-013.png](https://jira.catena-x.net/secure/attachment/23624/image-2024-01-17-07-04-45-013.png)

 

 

_Components_: N/A
_Sprints_: PI 12 - S1 - CPLP
_Fix Versions_: N/A
_StoryPoints_: N/A
_Attachments_: N/A

**Comment by manojava-gk** [comment]
@jjeroch Is new api available for this from portal back end?

**Comment by manojava-gk** [comment]
![Image](https://github.com/eclipse-tractusx/portal-frontend/assets/111366021/79ff8294-0665-48b2-b40c-acebfbb5515a)

Should be fine right? @jjeroch

**Comment by jjeroch** [comment]
@manojava-gk this ticket was marked for 24.03. please contact me if you can not make this milestone; otherwise we have a wrong documentation

**Comment by manojava-gk** [comment]
> @manojava-gk this ticket was marked for 24.03. please contact me if you can not make this milestone; otherwise we have a wrong documentation

This is in dev already..! Merged on 28th of Feb
