### ISSUE TITLE
Multiple Backend Calls and 404 Error on Company Certificate Page

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#463]
## Description
When clicking on "more" inside the company certificate page on a certificate page, multiple backend calls are running with one running on a 404 error. The reason for the 404 error is that the slash symbol is twice in a row added.

## Steps to Reproduce
1. Go to the company certificate page
2. Click on "more" button on a certificate page
3. Observe the multiple backend calls and the 404 error in the console

## Expected Behavior
Clicking on "more" button - system should only run needed backend calls and without any errors.
(note: calling GET /api/administration/companydata/company/BPNL00000003CRHK/companyCertificates should not be needed anymore - please let me know if we can get directly rid of it - if not, we need a own ticket for removing this endpoint from this part of the logic)

## Actual Behavior
Clicking on "more" button results in multiple backend calls and 404 error.

## Reproducibility
This issue is reproducible every time when following the steps above.

## Possible Solution
The double slash symbol should be removed or properly formatted to avoid the 404 error.
Additionally please check if the correct backend calls are connected - reason: even through we have a 404 error, we still see all needed information inside the UI.

## Environment
- Frontend application version: 1.7.0
- Browser: /companyCertificate

**Comment by jjeroch** [comment]
@manojava-gk please analyse the issue and share your result in the ticket; afterwards happy to help.

**Comment by manojava-gk** [comment]
API which provides data in details page needs bpn info(/{BPN}/companyCertificates). /ownCompanyDetails is being used to fetch the bpn info.  /companyCertificates end point without bpn number was giving 404 error. Now this is fixed by adding a check to the RTK query.
