### ISSUE TITLE
Marketplace App Card - Favorite Button

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#464]
### Summary

The current implementation of the favorite button is causing a problem. When a user clicks on the app's favorite button, the button icon does not change immediately. Instead, the change is only visible after reloading the page. The same issue occurs when trying to un-favorite an app.

### Expected Behavior:

When a user clicks on the favorite button, the button icon should change instantly to indicate successful favoritization.
Similarly, when un-favoriting an app, the button icon should update immediately.

### Steps to Reproduce:
- Open the app.
- Navigate to the marketplace - any app card
- Click on the favorite button.
- Observe that the button icon does not change immediately.
- Reload the page.
- Notice that the button icon now reflects the successful favoritization.

### Additional Information:
- This issue affects both favoriting and un-favoriting an app.
- The problem occurs consistently and is reproducible.
- The expected behavior is for the button icon to update instantly upon clicking, without the need for page reloading.

### Test 

- [ ] The button should switch and change immediately upon selection.
- [ ] The favorite section should be updated promptly when any favorite button of an app is selected.
- [ ] The favorite function should only be triggered when the user clicks on the exact favorite button and not anywhere else.
- [ ] Clicking the favorite button should not cause the card to reload.

**Comment by oyo** [comment]
To change this behavior and keep a satisfying user experience I recommend to change the hovering behavior of the card component slightly. Because currently the favorite button is in the expanded area of the card only visible when hovering over the card. If the user clicks the button the card is re-rendered and losing the expanded status. We could extend the hovering area to the whitespace under the card to prevent this.

**Comment by jjeroch** [comment]
> To change this behavior and keep a satisfying user experience I recommend to change the hovering behavior of the card component slightly. Because currently the favorite button is in the expanded area of the card only visible when hovering over the card. If the user clicks the button the card is re-rendered and losing the expanded status. We could extend the hovering area to the whitespace under the card to prevent this.

@manojava-gk  in case this is approached; please reach out to Dirk first

**Comment by manojava-gk** [comment]
> > To change this behavior and keep a satisfying user experience I recommend to change the hovering behavior of the card component slightly. Because currently the favorite button is in the expanded area of the card only visible when hovering over the card. If the user clicks the button the card is re-rendered and losing the expanded status. We could extend the hovering area to the whitespace under the card to prevent this.
> 
> [@manojava-gk](https://github.com/manojava-gk) in case this is approached; please reach out to Dirk first

No. but will talk to Dirk about this input.

**Comment by jjeroch** [comment]
Decided to re-design the app card (new hover state can get find below)
<img width="662" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/c45dfebd-dc08-4393-99fd-6274a1f0515c">

**Comment by manojava-gk** [comment]
<img width="597" alt="Screenshot 2024-03-29 at 12 37 01 PM" src="https://github.com/eclipse-tractusx/portal-frontend/assets/111366021/be544080-43e7-4ff7-9db5-9f6676671f05">
Reduced space by 30%
Description supported not bold
