### ISSUE TITLE
OSP Partner Invite | extId form field

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#477]
Detected in version: **1.8.0 RC3**
*likely already existing since 1.7.0

**Expected Situation:** 
When I enter a valid extId (6 digits, UUID character set) the onfiled validation should be alright and not warn me with a red border and exclamation mark.

 

**Actual Situation:** 
Please refer to the attached screenshot. 
<img width="159" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/88c569a7-028f-4a15-b266-02864c78c82a">

 

[Martin Rohrmeier](https://jira.catena-x.net/secure/ViewProfile.jspa?name=Martin.RA.Rohrmeier%40bmw.de)  the field should allow anything between 6 and 36 digits.

Please note that the tester (Leon) also recognized that if he clicks submit and afterwards tries to update the "extID" there is no change anymore to submit the registration again - the button is deactivated.

In parallel an backend ticket is getting created where the backend error need to get fixed: https://github.com/eclipse-tractusx/portal-backend/issues/482

**Comment by Leon-Gr** [comment]
Tested and verified on the INT environment.

**Comment by Leon-Gr** [comment]
Closing the issue due to completion.
