### ISSUE TITLE
Onboarding Service Provider UI - Confirmation Screen

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#484]
Summary
The current existing prototype implementation of the Onboarding Service Provider flow is supposed to get updated based on the final design.

https://www.figma.com/file/pcHZWXTQJUguIT75QSk9KW/Portal-Designs?type=design&node-id=8391-1119&mode=design&t=sSFdZh89CrP8VkWG-0

The implementation is divided into 4 tickets

- https://github.com/eclipse-tractusx/portal-frontend/issues/483
- https://github.com/eclipse-tractusx/portal-frontend/issues/484
- https://github.com/eclipse-tractusx/portal-frontend/issues/485
- https://github.com/eclipse-tractusx/portal-frontend/issues/486

<br>

`**In this ticket - the implementations of the confirmation screen is in focus**`

<br>

### Confirmation Page:

On this page, the user receives confirmation of the successful receipt of the registration and an overview of the current review status. 

The confirmation page consists of the following elements:

- Headline
- Subheadline
- Info text
- Subheadline
- Status with label /value of last update
- Overview of review steps with processing status (transfer from stock)
- "Get to home" button (change to start page)

 

#### Design

<img width="601" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/d802b197-6327-497d-a4d8-350f259400ec">

---

#### Acceptance Criteria

- [ ] after the successful submission of the company data& role, the registration status page is getting displayed (see design above)
- [ ]  all text values are configured
  * headline via locales files
  * description via locales files
  * field names via locales files
...NOTE: please do not add the translation into the main locales files. Instead a new file with the name "registration" is expected. This will ensure that we have the registration text in one area. Old text values from the prototype which have been added in the main locales file need to get cleaned up
- [ ] if the user clicks on "..home" the system will redirect the user to the {hostname}/home page

**Comment by nidhigarg-bmw** [comment]
@jjeroch To fetch the status lists, we need to call '/applications' API. Right ?

**Comment by jjeroch** [comment]
> @jjeroch To fetch the status lists, we need to call '/applications' API. Right ?

@nidhigarg-bmw yes correct - we use the same as for the others Get: /api/registration/applications
