### ISSUE TITLE
OSP IdP - disable & delete managed IdPs (FE)

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#489]
**Summary**

Enable the disablement and deletion of "Managed Idps".

Managed IdPs can only get disabled/deleted by the owner (this is the respective onboarding service provider); other users can neither deactivate nor delete the IdP.

 

**Details**

 Portal-Page: /idpmanagement
 
### Generic Logic

- [ ] Enable for MANAGED IdPs the sub-menu "Disable" and "Delete" - similar like for own idps - following validations are implemented

 * "Disable" is available in the sub-menu if the IdP is in "Active" state
 * "Disable" is only possible if another IdP in status "enabled: true" is existing
 * "Delete" is only available and possible if the IdP is in a disabled state
 * an IdP in "Disabled" state can get set "Active" again. All "Disabled" IdPs have the sub-menu "Activate" existing

<img width="154" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/af63b8c6-2ba9-436d-991a-8d6c8d0be916">

<img width="156" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/20e35f01-026f-43b5-868c-c76c38fc48c5">

- [ ] Important special implementation logic: neither the sub-menu "delete"; nor "activate" should be available if the IdP isOwner flag is "false" - the sub-menue "Disable" is existing, but always disabled with an tooltip on hover - text value:
   * de: "Nur IdP-Besitzer können den IdP deaktivieren"
   * en: "Only IdP Owners can disable the IdP"

 
### Implementation details "Disable" for managed IdP(s)

<img width="403" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/b6c178ef-eaa3-4427-ac21-11ecb508270a">

Figma: [https://www.figma.com/file/pcHZWXTQJUguIT75QSk9KW/Portal-Designs?type=design&node-id=8759-4683&mode=design&t=RTcvNOsuhgD98KZW-0]

- [ ] in the scenario of disabling the IdP - an overlay is needed for the Managed Type
 * as long as the endpoint is called and no response is available, a load element is displayed and "Disable" can't get triggered a second time
 * get the GET /api/administration/identityprovider/network/identityproviders/managed/\{identityProviderId} and validate the content under "connectedCompanies"
 * display an overlay explaining the user the deactivation impact
   * de: "Bei der Deaktivierung des Identitätsanbieters bleiben alle Daten erhalten, der Zugriff wird jedoch gesperrt. Bitte achten Sie darauf, sich selbst bzw. Ihre Organisation nicht auszusperren. Die folgende Liste gibt einen Überblick über alle Organisationen, die bei der IdP-Verbindung registriert sind."
   * en: "With the deactivation of the identity provider - all data will remain, however the access will be blocked. Please ensure to not lock out yourself/your organization. Below list gives an overview all all organizations registered at the IdP connection."
 * Section 2 text values
   * de: "Die Kunden werden über die Deaktivierung informiert. Eine Kommunikation der geplanten Deaktivierung von der IdP Owner Seite wird trotzdem stark empfohlen."
   * en: "The customer(s) will be informed of the deactivation. Communication of the planned deactivation from the IdP owner side is still strongly recommended."
- [ ] when clicking on "disabled" inside the overlay, the POST /api/administration/identityprovider/owncompany/identityproviders/{identityProviderId}/status endpoint is triggered
- [ ] while the api is running, the button shows an load element and the user is not able to retrigger the process

### Implementation details "Delete" for managed IdP(s)

<img width="400" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/6b9af197-e3e5-448e-b920-7a26ffb6e978">

- [ ] clicking on "Delete" in the sub-menu opens a overlay
- [ ] inside the overlay the text values are displayed:
- Section 1
  - de: "Sie sind dabei, diesen IdP zu löschen. Mit der Löschung des Identity Providers werden verbundene Unternehmen gelöscht bzw. auf gelöscht gesetzt. Überprüfen Sie die Liste der verbundenen Unternehmen sorgfältig und stellen Sie sicher, dass diese informiert sind, bevor Sie fortfahren."
  - en: "Your are about to delete this IdP. With the deletion of the identity provider - connected companies will get deleted or/and set to deleted. Validate the list of connected companies carefully and ensure that those are informed before proceeding."
- Section 2
  - de: "Der Vorgang kann nicht rückgängig gemacht werden."
  - en: "The process cannot be reversed."
- [ ] when clicking on "delete" inside the overlay, the DELETE /api/administration/identityprovider/owncompany/identityproviders/{identityProviderID} endpoint is triggered
- [ ] while the api is running, the button shows an load element and the user is not able to retrigger the process
 
- [ ] the successful disabling is shown with a snackbar on the top right, the IdP status should get updated inside the FE screen immediately
- [ ] in case of an unsuccessful deactivation, display the same inside the overlay and keep the overlay open
- [ ] the successful deletion is shown with a snackbar on the top right, the IdP status should get updated inside the FE screen immediately

 

 

Swagger: [https://portal-backend.dev.demo.catena-x.net/api/administration/swagger/index.html]

Endpoint: GET /api/administration/identityprovider/network/identityproviders/managed/{identityProviderId}

 
---

+Linked Tickets:+

CPLP-3194

CPLP-3323

**Comment by lavanya-bmw** [comment]
@jjeroch, the below section is not implemented as discussed.

 Important special implementation logic: neither the sub-menu "delete"; nor "activate" should be available if the IdP isOwner flag is "false" - the sub-menue "Disable" is existing, but always disabled with an tooltip on hover - text value:
de: "Nur IdP-Besitzer können den IdP deaktivieren"
en: "Only IdP Owners can disable the IdP"
