### ISSUE TITLE
Technical User Details - quotation marks are vizualised

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#492]
Detected in version: **v.1.8.0 RC3**
*probably already since RC1 existing

**Summary**

Quotation marks displayed in the UI - this is not needed
Page: /techuserdetails/{technicaluserID}

<img width="947" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/33f6bb99-9959-4dbe-b006-47fc018b2dd5">

**Comment by lavanya-bmw** [comment]
PR link: https://github.com/eclipse-tractusx/portal-frontend/pull/512

**Comment by jjeroch** [comment]
@lavanya-bmw  UI looks good, but when using the copy icon I still get the information copied into my clipboard with quotation marks. As soon as the IdP "Decline" and "Deactivation" is done, please check this one once again
