### ISSUE TITLE
App Subscription Request Configuration Overlay - Help Buttons do not work

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#493]
Env.: Dev

Account: CX-Operator

As-is:

<img width="696" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/2ee2413f-1360-481f-ade3-9d4b9401da61">

when clicking on any of the "Help" links, an incorrect page is getting displayed:

<img width="888" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/f170d1b5-0004-4ce7-81b9-b49b5764d47e">

To-Be:

The actual page should get displayed

**Comment by lavanya-bmw** [comment]
@jjeroch Fixed help links in app release process and service release process and merged to dev.
