### ISSUE TITLE
Consent Pop-Up after registration via OSP erroneous and missing status overvlay

### ISSUE THREAD

**Issue by Leon-Gr** [eclipse-tractusx/portal-frontend#519]
### Current Behavior
After an OSP registered a partner, this partner receives a welcome mail. After clicking the link and logging in the partners is greeted by a pop-up asking for consent for the T&Cs. After confirming and submitting the consent, the pop-up window closes. 

However every time a new page is visited now, the pop-up comes back up. The confirmation is still set (the boxes are still checked) and the pop-up window needs to be closed to proceed browsing the site.

### Expected Behavior
After giving consent, the pop-up should not show up every time a new page is visited. Additionally, what is expected is the "usual" status overlay flow as described here: [JIRA-Ticket](https://jira.catena-x.net/browse/CPLP-3577 )

**Comment by jjeroch** [comment]
Please note, the bug is created in relation of testing the implementation of https://github.com/eclipse-tractusx/portal-frontend/issues/468
