### ISSUE TITLE
Adapt OSP/IdP Register Partner Overlay Text

### ISSUE THREAD

**Issue by Leon-Gr** [eclipse-tractusx/portal-frontend#521]
### Current Situation
Currently the overlay that appears after clicking "Register Partner" on a managed IdP has a placeholder text in the upper section.

### Aimed For Situation
The placeholder text should be replaced by the following:
"This registration form only serves as a mock, that allows to register partners. In the future this functionality is not planned to exist further. The partner registration will then happen utilizing a technical user."

**Comment by jjeroch** [comment]
@Leon-Gr  we can do the change directly by ourself.
If you have time, please do the update; if not Johannes or myself can support.

File:
https://github.com/eclipse-tractusx/portal-frontend/blob/release/v1.8.0-RC6/src/assets/locales/en/idp.json
row: 277 ff.

**Comment by Leon-Gr** [comment]
Closed with merge
