### ISSUE TITLE
Change app roles - roles not showing

### ISSUE THREAD

**Issue by johanneskueffner** [eclipse-tractusx/portal-frontend#553]
### Current Behavior
When trying to add new roles to an existing app, the already existing roles are not shown and only purple rectangles are displayed
### Expected Behavior
The screen should display the already existing roles
### Steps To Reproduce:
Try to add new roles to an existing app via the three dots in the app overview
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/71873124/4bfe9982-d34f-4d88-81fc-d2f2a91f6b9b)
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/71873124/01844906-3d7a-463f-a22f-fb302f504b69)

**Comment by lavanya-bmw** [comment]
@jjeroch API response is empty([]). This should be fixed from BE.
In FE, I have fixed empty chip display issue when response is empty.

**Comment by jjeroch** [comment]
@lavanya-bmw  i think we need to re-do the ticket as soon as we received the delivery of https://github.com/eclipse-tractusx/portal-backend/issues/573
