### ISSUE TITLE
App release process - selected usecases not displayed

### ISSUE THREAD

**Issue by johanneskueffner** [eclipse-tractusx/portal-frontend#554]
### Current Behavior
After selecting one or more usecases in the app release process, it shows an corrosponding amount of purple rectangles

### Expected Behavior
The selected usecases should be  shown

### Steps To Reproduce
During the app release process, select one or more usecases
<img width="700" alt="MicrosoftTeams-image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/71873124/f82333f4-a7cd-4072-857f-c21b293d4f76">

**Comment by lavanya-bmw** [comment]
@jjeroch This issue occurred during fixing linter findings
