### ISSUE TITLE
TRG 1.02 appropriate install instructions either `INSTALL.md` or in `README.md`

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/portal-frontend#562]
Hi TRG fullfilled but some small remarks on Linking Installation guides

https://github.com/eclipse-tractusx/portal-frontend/blob/5768d34fbb215903a12535bc3b52a5a60d735bf9/README.md?plain=1#L37-L39

could be separated with single lines to copy and i guess the var for `IMAGE` could also left out, but it is just a style thing.

like 
Pull our latest image

```bash
docker pull tractusx/portal-frontend:latest
```

run it local or some similar wording
```bash
docker run --rm -d -p 3001:8080 --name cx-portal-frontend tractusx/portal-frontend:latest
```

also some hint:
https://github.com/eclipse-tractusx/portal-frontend/blob/5768d34fbb215903a12535bc3b52a5a60d735bf9/README.md?plain=1#L21

i would link the document itself directly into your install instructions, will prevent people for searching: 
https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/Run%20frontend%20on%20localhost.md

Also maybe a little hint that are many information about Catena-X references and calling that could be rechecked.

**Comment by evegufy** [comment]
@FaGru3n thanks for the hints, I updated the readme, please check the release branch https://github.com/eclipse-tractusx/portal-frontend/tree/release/v1.8.0
I removed a couple for the docker related information as it's a bit obsolete and more confusing than helpful.

**Comment by FaGru3n** [comment]
> also some hint:
> 
> https://github.com/eclipse-tractusx/portal-frontend/blob/5768d34fbb215903a12535bc3b52a5a60d735bf9/README.md?plain=1#L21
> 
> i would link the document itself directly into your install instructions, will prevent people for searching: https://github.com/eclipse-tractusx/portal-assets/blob/main/docs/developer/Technical%20Documentation/Dev%20Process/Run%20frontend%20on%20localhost.md
> 
> Also maybe a little hint that are many information about Catena-X references and calling that could be rechecked.

you want also adapt this or should i close this...

**Comment by evegufy** [comment]
@FaGru3n sorry forgot to give an update regarding that point. No, I won't do it for now. Would be nice in general but such links are hard to maintain throughout the release process if one references to a tag, which would be the proper solution (fyi, I do that within [chart readme](https://github.com/eclipse-tractusx/portal/blob/release/v1.8.0/charts/portal/README.md), but doing this for every readme is hart to maintain). I don't want to just reference to main, as that could lead to confusion.

**Comment by FaGru3n** [comment]
sure no breaking changes just try to help improve a little bit, unless you´re doing it in the chart readme... just optionial and as i said a hint... not a "must" 

so will close the issue after your input on the first hint.
