### ISSUE TITLE
TRG 4.06 separate Docker-Notice file notice-portal.md could be renamed

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/portal-frontend#565]
In Fact you have a separate `DOCKER_NOTICE.md` file but need maybe a little renaming.

https://github.com/eclipse-tractusx/portal-frontend/blob/v1.8.0-RC6/.conf/notice-portal.md

and workflow then also need to updated.
https://github.com/eclipse-tractusx/portal-frontend/blob/7e06f7330bfecd55a1a4e88e0c172ef71ef3eaa6/.github/workflows/release.yml#L125

**Comment by evegufy** [comment]
@FaGru3n thanks for the observation! I'll look into the change for the release. Could you please rename the issue so that it doesn't appear as if this repo wouldn't have a separate docker notice. Thank you!
