### ISSUE TITLE
Update dash tool in dependencies check workflows

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/portal-frontend#566]
https://github.com/eclipse-tractusx/portal-frontend/blob/v1.8.0-RC6/scripts/download/org.eclipse.dash.licenses-1.0.2.jar

could be updated latest version i found is org.eclipse.dash.licenses-1.1.1

https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=LATEST

and your docs how to use it could be moved and changed to `docs/` folder and changed to 

https://github.com/eclipse-tractusx/portal-frontend/blob/v1.8.0-RC6/scripts/check-dependencies.md

```bash
curl -L --output ./scripts/download/org.eclipse.dash.licenses-1.1.1.jar 'https://repo.eclipse.org/service/local/artifact/maven/redirect?r=dash-licenses&g=org.eclipse.dash&a=org.eclipse.dash.licenses&v=1.1.1'
```

**Comment by evegufy** [comment]
@FaGru3n thanks for the observation! it's on our list of maintenance tasks.
