### ISSUE TITLE
TRG 7.07 Legal notice for documentation

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/portal-frontend#567]
some Legal Notice infromation are missing for your documentation 
https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-07#documentation

Maybe this could also placed under the `docs/` folder
https://github.com/eclipse-tractusx/portal-frontend/blob/v1.8.0-RC6/scripts/check-dependencies.md
https://github.com/eclipse-tractusx/portal-frontend/blob/v1.8.0-RC6/FILEHEADER.md

**Comment by evegufy** [comment]
@FaGru3n thanks for the hint, change is implemented, please check the release branch https://github.com/eclipse-tractusx/portal-frontend/tree/release/v1.8.0
