### ISSUE TITLE
TRG 2.05 `.tractusx` metafile in a proper format

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/portal-frontend#568]
small updates to metafile

**Comment by evegufy** [comment]
@FaGru3n thanks but this is already addressed by https://github.com/eclipse-tractusx/portal-frontend/pull/561

**Comment by evegufy** [comment]
@FaGru3n change is implemented, please check the release branch https://github.com/eclipse-tractusx/portal-frontend/tree/release/v1.8.0
