### ISSUE TITLE
Roles&Rights matrix not displayed

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#576]
Detected in version: **v.1.8.0**

### Summary
Image displayed on the page `https://portal.int.demo.catena-x.net/role-details - roles comparision` is not getting displayed anymore.
Make sure the image is fetched from the correct folder

https://github.com/eclipse-tractusx/portal-assets/blob/501d2269125b9699287e35ab6b0558a1841c9073/docs/static/PortalRoleAndPermissionMatrix.png (note, the shared url is the branch url; we need to ensure that we dont fetch the specific committ/branch but rather have a real link)

**Comment by evegufy** [comment]
@jjeroch @nidhigarg-bmw I looked at the issue and will take it over.

**Comment by evegufy** [comment]
explanation: the two images `PortalRoleAndPermissionMatrix.png` and `RegistrationRoleAndPermissionMatrix.png` were moved from /public/assets/images/docs to docs/static as part of https://github.com/eclipse-tractusx/portal-assets/pull/238/commits/caef999ddd6f9be3b0c75d957365d1c7e6b05c40
but apparently those two images aren't used by the documentation app but by the portal app, therefore I move those two images to images/content to avoid further with images used by the documentation app 
those two images are the only affected images by this move, as all other moved images are only referenced in the documentation app.
