### ISSUE TITLE
Connector Overview & Detail Page

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#577]
### Summary
With the latest release of SSINext, the connector management function need to get refactored.

- [ ] update the page url and navigation headline for the connector registration management from "/technicalsetup" to "/connectormanagement"
- [ ] Update all links and references within the application from "/technicalsetup" to "/connectormanagement"
- [ ] Implement 301 redirects from the old URL to the new URL to maintain SEO value and prevent 404 errors for users who have bookmarked the old URL.
- [ ] Update any relevant API calls that may be affected by the URL change. (expected to be none; but please check once)
- [ ] rename the first connector table header from "Onboarded Connectors" to "Owned Connectors"
- [ ] add "connectorUrl" inside the table
- [ ] add "details button"
- [ ] add details page (displaying status, url, SD document for download)
- [ ] remove location (will only get displayed inside the detail page)
<br>

Wireframe

<img width="523" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/cfdb87f5-0b7b-4e40-a192-e27af62c66ce">

---

https://www.figma.com/file/olKk06eVXHIOZUtrcQbgcB/UX?type=design&node-id=4012-413&mode=design&t=gJRbe2Ahyydn65LX-0

---

Connectore Main Page

### View Connector Details
When clicking on the main page on connector detail button, the overlay with the connector details get displayed.
To display the connector details the following endpoint is called

**Endpoint:** `GET /api/administration/Connectors/{connectorId}`

`Name`: "name": "string"
`URL`: 
`Status`: "status": "PENDING"
`Type`: "type": "COMPANY_CONNECTOR"
`Host`: "hostCompanyName": "string"
`Location`: "location": "string"
`SD Registration`: the checkbox should be ticked and active if a "selfDescriptionDocumentId" exist; otherwise unticked and inactive 
`SD Document`:  download document icon

`Note - currently missing: technical user link - need to get added. UX Team is already informed`

- [ ] as long as information are loaded by the backend, the overlay display the load button - same as lately implemented by Nidhi in the registration status overlays
- [ ] any icon hovering is implemented in the known way (highlighting the icon)
- [ ] if a document is available - the user can download it by clicking on the document
- [ ] the "learn more" button is deactivated for now

**Special Scenarios**

If data cant get loaded due to a 5xx html error:

<img width="527" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/fe1f34a5-24ee-4ccd-add7-a008d8dbf28a">

If data cant get loaded due to a 4xx html error:

<img width="623" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/887f9e44-5446-448b-a49d-c88dba220d58">

<br>
<br>

### Edit Connector 
The user is able to edit the connector url if the permission `modify_connectors` exists.

<img width="449" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/1527231c-6cff-4f96-8aab-4be793afc242">

When clicking on the edit button the field will change to an input field displaying an information as defined in the wireframe to the user

<img width="413" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/0509e0f2-f4f3-4388-a036-82a8bcfdf07a">

In case of errors while entering the new URL

<img width="489" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/34394db7-d59a-4b74-90d7-5458f0222203">

In case of errors while submitting API data to the endpoint

<img width="497" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/58f1810b-572d-41d7-9b7d-90c550b32d4d">

<br><br>

**Endpoint:**`PUT /api/administration/Connectors/{connectorId}/connectorUrl`

```json
{
  "connectorUrl": "string"
}
```

<br>
<br>

### Delete Connector 
Delete Connector button is clickable if the user has the respective needed permission `delete_connectors`

**Endpoint:**`DELETE /api/administration/Connectors/{connectorId}`

```json
n/a
```

<img width="803" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/4209732b-c006-4be8-8c8f-a9872fbe0e47">

<br>
<br>

...

Linked BE changes
https://github.com/eclipse-tractusx/portal-backend/issues/546
https://github.com/eclipse-tractusx/portal-backend/issues/547
https://github.com/eclipse-tractusx/portal-backend/issues/548
https://github.com/eclipse-tractusx/portal-backend/issues/549

**Comment by jjeroch** [comment]
@lavanya-bmw I have a couple of updates to this ticket.
Figma: https://www.figma.com/file/pcHZWXTQJUguIT75QSk9KW/Portal-Designs?type=design&node-id=10325-2429&mode=design&t=O49z07U0ntoWn0TB-0

Design Main Page

![Image](https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/6d680b23-e1a0-463c-ad95-6b22987aec59)

**Comment by lavanya-bmw** [comment]
@jjeroch, edit icon is available for name but in BE, it supports only url, so added edit for url alone

**Comment by lavanya-bmw** [comment]
@jjeroch As discussed, I have added link for technical user(details), which on click navigates to '/techuserdetails/id' 
@evegufy Fixed https://github.com/eclipse-tractusx/portal-frontend/issues/924 issue
