### ISSUE TITLE
Code Maintenance - remove unused code (overlays)

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#578]
### Summary
in the current portal code; a number of unused code is existing.
Delete unused code e.g. overlays

### How to approach

- check the code
- run through the overlays and validate unused code/overlays
- send an overview of the analysis to the PO
- jointly validate the list with the PO
- remove unused overlays

**Comment by jjeroch** [comment]
@oyo anything you like to add?

**Comment by oyo** [comment]
> @oyo anything you like to add?

@jjeroch Nothing to add - I approve this approach

**Comment by nidhigarg-bmw** [comment]
I found below overlay files which are not in use
- /overlays/TechnicalUserInfo
- /overlays/IDPDelete
- /overlays/IDPStatusChange
- /overlays/IDPTestRun
- /overlays/SampleForm
- /overlays/DeleteIDP
- /overlays/EnableIDP/DisableIDP

**Comment by jjeroch** [comment]
@nidhigarg-bmw thanks looks good. Quick check on the /overlays/IDPDelete & /overlays/EnableIDP/DisableIDP - Lavanya has recently implemented a function related to that; I guess those got a new overlay name?

**Comment by lavanya-bmw** [comment]
I worked on DeleteManagedIdp and DisableManagedIdp components

**Comment by nidhigarg-bmw** [comment]
> @nidhigarg-bmw thanks looks good. Quick check on the /overlays/IDPDelete & /overlays/EnableIDP/DisableIDP - Lavanya has recently implemented a function related to that; I guess those got a new overlay name?

@jjeroch So does make sense to delete these overlays as well ?

**Comment by jjeroch** [comment]
@nidhigarg-bmw  yes fine
