### ISSUE TITLE
CSS Definitions: Remove duplicate / unused css definition - 

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#583]
### Summary
CSS Definitions: Remove duplicate / unused css definition
perform a cleanup of the CSS definitions in the application codebase. This cleanup involves removing duplicate and unused CSS definitions to improve the application's performance and maintainability.

Tasks:
- Identify and remove duplicate CSS definitions across the codebase. These duplicates may have been created due to copy-pasting or inheritance from different sources.
- Identify and remove any unused CSS definitions that are no longer being used in the application. These unused definitions may have been left over from previous iterations or changes to the application.
- Refactor the CSS definitions to ensure consistency and readability across the codebase.

**Comment by nidhigarg-bmw** [comment]
@jjeroch As discussed with Martin, he suggested that the build will already sort out unused css. We only go quickly through all folders and check if every (s)css is at least imported somewhere once that should be enough.
