### ISSUE TITLE
Technical User Management - enable inactive overview

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#585]
### Summary
Till now service account endpoints only support ACTIVE technical account details.

However it is likely that the Company Admin/IT Admin also wants to receive access of the technical user account history of probably DELETED technical users.

**2 Options:** 

- enhance the existing endpoint with an optional filter
- new endpoint

**Decision:** enhance existing endpoint instead of adding new endpoints.

 

#### Where?
Enhance the view chipcards by adding a card for "inactive" users
<img width="428" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/585f274b-49ed-4b0d-b473-7bb7d564a58f">

**API Endpoint** to fetch inactive technical users for technical user table `GET /api/administration/serviceaccount/owncompany/serviceaccounts?filterForInactive=true'`

**API Endpoint** to fetch inactive technical users details (for the detail screen) `GET /api/administration/serviceaccount/owncompany/serviceaccounts/{serviceAccountId}` ...this is exactly the same endpoint as used for active technical user details

NOTE: regarding the chipcard design - please check once with Anni regarding the to be used chipcard/text color. Ideally its a bit different to our current used chipcards since we are displaying none active users

**Comment by nidhigarg-bmw** [comment]
@jjeroch Anne suggested to create button for 'Inactive' as below link and before the 'ALL' chip. Does it okay for you ?

https://www.figma.com/file/pcHZWXTQJUguIT75QSk9KW/Portal-Designs?type=design&node-id=9168-198&mode=design&t=JcPSlsUMjxi6cszJ-0

**Comment by jjeroch** [comment]
@nidhigarg-bmw Anni her feedback is missing. i will see her at 10am - for now I would for sure say that we:

- change the "All" Button to "Active"
- add an "Inactive" button beside
