### ISSUE TITLE
Connect Registration Decline Button with Backend API Call

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#618]
## Summary
connect the registration decline button on the page `/decline` with the backend API call that has been delivered by the backend team. This will allow users to decline their registration and trigger the necessary actions on the server side.

## Details
1. Identify the location of the registration decline button on the page `/decline`.
2. Update the frontend code to handle the click event of the decline button.
3. Implement the API call to the backend using the provided endpoint.
    POST /api/registration/application/{applicationId}/declineRegistration
4a. Handle the response from the backend API call and display with success response the successful decline screen to the user
4b. Make sure to handle any potential errors or edge cases that may occur during the API call or response handling.
6. Test the functionality to ensure that the registration decline process works as expected.

## Acceptance Criteria

- [ ] The registration decline button on the page `/decline` triggers the backend API call when clicked.
- [ ] The API call is made to the correct endpoint
- [ ] The response from the backend API call is handled correctly and appropriate feedback is displayed to the user.

`Note - the implementation of the FE screens have been already delivered as part of 24.03 - only the missing api connection is taking place now`

**Comment by nidhigarg-bmw** [comment]
@jjeroch API is added but not able to test it. As discussed with @Leon-Gr was not able to invite user so can access the decline page and test the API.
