### ISSUE TITLE
Connect Credential Management UI with new Issuer Component

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#620]
### Summary
This ticket covers the update of the credential management function.
The current existing implementation has a breaking change, the portal endpoints and backend logic have been moved into a new component. Due to this change, the frontend integration needs to get updated.

### Details

**Page:** `/usecase-participation`
**Current Used Endpoint:** `GET /api/administration/companydata/useCaseParticipation`
**New Endpoint:** `GET https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer/useCaseParticipation`

*Please test with the new endpoint on dev and ensure that informations are successfully retrieved and displayed.

---

**Page:** `/usecase-participation`
**Current Used Endpoint:** `POST /api/administration/companydata/useCaseParticipation`
~~**New Endpoint:* `POST https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer/framework`~~

~~NOTE: the new endpoint can not support any document.~~
~~Please update the FE code. The overlay displayed to the user should only request for the checkmark the document~~
~~upload function should get commented out (..not deleted; only commenting out please)~~

~~*Please test with the new endpoint on dev and ensure that informations are successfully retrieved and displayed.~~

---

**Page:** `/admin-credential`

- Change the name of the page (inside the menu/navigation) to `Certification Mgmt` to `Credential Requests`

---

**Page:** `/admin-credential`
**Current Used Endpoint:** `GET /api/administration/companydata/credentials?page=0&size=10&companyName=&companySsiDetailStatusId=`
**New Endpoint:** `GET https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer`

*Please test with the new endpoint on dev and ensure that informations are successfully retrieved and displayed.
Make sure that search and filters, etc. are still working as well as pagination.

##### Sorting
https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer?sorting=BpnlAsc
https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer?sorting=BpnlDesc

##### Filtering by credential request status
e.g. https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer?companySsiDetailStatusId=PENDING

##### Filtering by credential type
e.g. https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer/swagger/index.html

**Swagger:** https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer/swagger/index.html

---

**Comment by jjeroch** [comment]
@nidhigarg-bmw  first set of informations added. more to follow

**Comment by jjeroch** [comment]
@nidhigarg-bmw ready to start

**Comment by nidhigarg-bmw** [comment]
@jjeroch Getting CORS error for SSI credential api's
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/101316912/65a0ab2c-de60-4dcc-93d8-bfb8c2df16f5)

**Comment by evegufy** [comment]
@nidhigarg-bmw as just discussed, please use the client `Cl24-CX-SSI-CredentialIssuer`

cc: @jjeroch

**Comment by evegufy** [comment]
> @nidhigarg-bmw as just discussed, please use the client `Cl24-CX-SSI-CredentialIssuer`
> 
> cc: @jjeroch

ok after some additional analysis the client doesn't need to enabled, there error from [here](https://github.com/eclipse-tractusx/portal-frontend/issues/620#issuecomment-2072418560) was due to wrong ssi-credential-issuer host being used.
it's solved now.

**Comment by nidhigarg-bmw** [comment]
@jjeroch For this API,
https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer?page=0&size=10
previously we have only document object ie
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/101316912/16c399bb-6e3d-47c4-b2da-cae1cd160d6f)
and in ssi-issuer url we have array of documents 
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/101316912/3ba4314e-f848-4fdb-8d3a-a455cc243544)

How to handle this ?

**Comment by jjeroch** [comment]
> @jjeroch For this API, https://ssi-credential-issuer.dev.demo.catena-x.net/api/issuer?page=0&size=10 previously we have only document object ie ![image](https://private-user-images.githubusercontent.com/101316912/325998681-16c399bb-6e3d-47c4-b2da-cae1cd160d6f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MzA4NTIsIm5iZiI6MTcxNDQzMDU1MiwicGF0aCI6Ii8xMDEzMTY5MTIvMzI1OTk4NjgxLTE2YzM5OWJiLTZlM2QtNDdjNC1iMmRhLWNhZTFjZDE2MGQ2Zi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQyMjQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1iODVmNmVlZTE5ZGJmZDdmNjkyOWVmNTllYmYwYzllYjAzYTViMmI0MDY3NzM5YzkwY2UwZjg4YWZmNGExNDVhJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.rgRKE50vcQpQBPbLE-hNAbDntmQ7GQhyTr583C8R_Kc) and in ssi-issuer url we have array of documents ![image](https://private-user-images.githubusercontent.com/101316912/325998730-3ba4314e-f848-4fdb-8d3a-a455cc243544.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0MzA4NTIsIm5iZiI6MTcxNDQzMDU1MiwicGF0aCI6Ii8xMDEzMTY5MTIvMzI1OTk4NzMwLTNiYTQzMTRlLWY4NDgtNGZkYi04ZDNhLWE0NTVjYzI0MzU0NC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDI5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyOVQyMjQyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNjNlODlhZTJlYTE0M2VjYjU5ZGNlY2M3YTc4NDFiMTk1ODM2Zjc3YWQ4YjIyYzc0YTMxOWM5ZWJkMTdmMzIxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.MPvasUOKHTFLCwNGUchkfH2hOSUMfysoCX__k-FfD7o)
> 
> How to handle this ?

@nidhigarg-bmw please do the following: for now (there will be still a correction in the endpoint response) only display the first document.
