### ISSUE TITLE
Implementation of New UI Design for Company Certificates

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#622]
##Summary
This ticket involves the implementation the new UI design for company certificates based on the existing prototype `/companyCertificate`. The goal is to update the frontend of the application to reflect the new design and provide a visually appealing and user-friendly interface for managing company certificates.

Tasks
1. Review the provided new UI design for company certificates and understand the design requirements.
2. Update the existing frontend codebase to incorporate the new design elements and styles.
3. Implement responsive design principles to ensure the application is visually appealing and functional on different devices and screen sizes.
6. Ensure that the new UI design is consistent with the overall application design and branding.

### Design

![Version 1 (9)](https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/bf8bb06a-d9d7-4718-9c7f-792dda9ccd0a)

---

**Acceptance Criteria:**

- [ ] Update the filters to only support 
  - All certificates
  - Active
  - Inactive
- [ ] Make sure that switching around across the filters works without any issues
- [ ] add the MUI upload icon to the "Certificate Upload" button
- [ ] add the page description details
  - en: "Efficiently manage and organize your company certificates with ease. This page provides a user-friendly interface to view, add, edit, and delete company certificates. Stay on top of your certificate management process and ensure compliance effortlessly."
  - de: "Verwalten und organisieren Sie Ihre Unternehmenszertifikate einfach und effizient. Diese Seite bietet eine benutzerfreundliche Oberfläche zum Anzeigen, Hinzufügen, Bearbeiten und Löschen von Unternehmenszertifikaten. Behalten Sie den Überblick über Ihren Zertifikatsverwaltungsprozess und stellen Sie mühelos die Einhaltung sicher."
- [ ] Switch the document cards to the new design; ensure to go for a low maintenance effort card and do not design them to huge
- [ ] MUI Warning Icon to be displayed on the app card as soon as expiry date is < "today+30days"
- [ ] Keep the sub-menu with "view" and "delete" but ensure the correct typo and size usage as well as the sub-menu action when clicking outside the element
- [ ] keep the overlay as implemented in the prototype
- [ ] the user should not be allowed to submit a certificate without given "valid till" date

**Comment by manojava-gk** [comment]
<img width="666" alt="Screenshot 2024-04-01 at 3 56 57 PM" src="https://github.com/eclipse-tractusx/portal-frontend/assets/111366021/95cbf9bb-593a-41c2-acf6-f27f38fa9c52">
Let me know your thought on this implementation @jjeroch 

1. Have added tooltip msg on each icon - warning, checked and closed icons
2. Warning icon will appear if certificate is expired or about to expire in 30 days
3. Close icon will appear when certificate in INACTIVE state
4. Check icon for active state
5. Delete icon will appear if user has proper access and certificate in ACTIVE state

In my opinion, we can remove the dots from the card as icon representation is more effective
