### ISSUE TITLE
sig#810: Manage Company Data UI

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#623]
`Ticket Under Creation`

#### Summary:
Implement a new feature in the existing application that allows users with the appropriate permissions to manage company data. This includes viewing and managing legal entity data, subsidiaries, company locations (BPNSs), and specific addresses (BPNAs).

#### Details:

Figma:
https://www.figma.com/file/olKk06eVXHIOZUtrcQbgcB/UX?type=design&node-id=3871-4&mode=design&t=PhBMDkTbkDIfmcod-0

![Image](https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/9cfb5461-4d30-4b0b-a593-29fc74c72123)

1. **User Authentication:**
   - Ensure that only users with the necessary rights can access the data management panel.
   - Permission: `company_data` (note not yet existing - working on it)

2. **Data Management Panel Integration:**
   - Integrate the new panel into the existing application seamlessly.
   - The panel should be accessible via a clear and intuitive navigation path.

3. **View Records:**
   - Users should be able to view a list of legal entities, subsidiaries, BPNSs, and BPNAs.

4. **Add New Records:**
   - Users should be able to add new legal entities, subsidiaries, BPNSs, and BPNAs.
   - Ensure that the addition of new records is user-friendly and validated client-side before submission.

5. **Edit Records:**
   - Users should be able to edit existing legal entities, subsidiaries, BPNSs, and BPNAs.
   - Ensure that edits are validated client-side before submission.

6. **Delete Records:**
   - Users should be able to delete existing legal entities, subsidiaries, BPNSs, and BPNAs with proper confirmation prompts to prevent accidental deletions.

7. **Workflow Integration:**
   - Implement a workflow for record changes with the statuses: Pending, Error, and Active.
   - New entries and changes submitted should initially be marked as "Pending" and go through a validation process.

8. **Validation Process:**
   - After submission, the entry should remain "Pending" until the validation process is complete.
   - If validation is successful, the status should change to "Active".
   - If validation fails, the status should be set to "Error", and the user should be able to view and correct the errors.

9. **Error Handling:**
   - Users should be able to refresh the screen to view any possible errors.
   - Provide clear and informative error messages to guide the user through the necessary steps to correct the data.

10. **Backend Integration:**
    - Prepare the frontend to connect with the BPDM interfaces for data handling.
    - Ensure that the frontend handles asynchronous operations and displays loading states appropriately.

11. **UI/UX:**
    - Design a clean and modern user interface consistent with the existing application's design language.
    - Ensure that the UI is responsive and accessible across different devices and browsers.

#### Technical Notes:
- The frontend should be implemented using the existing tech stack of the application.
- Ensure that the code follows best practices for security, performance, and maintainability.

#### Dependencies:
- Backend endpoints for BPDM interfaces are not yet existing - will get provided by BPDM asap
- UI/UX design under finalization

Please ensure that all the acceptance criteria are met before submitting the task for review. If there are any blockers or clarifications needed, reach out to the project manager or team lead as soon as possible.

**Comment by jjeroch** [comment]
@manojava-gk  api endpoints not yet available. Please check if we can start based on the UX wireframes using shared components for realization

**Comment by manojava-gk** [comment]
@jjeroch could you pls recheck about the delete function?

**Comment by jjeroch** [comment]
`Updates ongoing this week to add all endpoint details`

@manojava-gk tackling the API connection
Attached the postman collection
[BPDM Tests.postman_collection.json](https://github.com/eclipse-tractusx/portal-frontend/files/15052785/BPDM.Tests.postman_collection.json)

**View Records**
Call all the records (note this call includes pagination)
Call `GET {portal gate url*}/v6/input/business-partners/search?page=0&size=30`
*please check with Evelyn...must be the same as we are using for PUSH/PULL process step of the registration approval process

Inside the body send an empty string

`
[
  ""
]
`

---

**Create Site**
Create a new Site
Call `POST ???`

- Users BPNL to be added inside legalEntityBpn
- Add site.siteName 
- isOwnCompanyData to be set to ‚true‘
- addressType to be set to ‚SiteMainAddress‘

---

**Comment by jjeroch** [comment]
Target Release updated, we wont make 24.05. in time - we are planning an interim release version in June

**Comment by MaximilianHauer** [comment]
@manojava-gk  was there the active request from @jjeroch  to create a new page and  not include it into "my Company" ? i dont understand why we have two seperate pages with the nearly same content.

**Comment by evegufy** [comment]
@MaximilianHauer I suggest to close this issue

**Comment by MaximilianHauer** [comment]
@manojava-gk  what was the decision on the delete ? i assume there is no delete endpoint ? couldnt find any in the bpdm swagger

**Comment by manojava-gk** [comment]
delete is not available @MaximilianHauer
