### ISSUE TITLE
Portal dev base url is not loading up the data 

### ISSUE THREAD

**Issue by manojava-gk** [eclipse-tractusx/portal-frontend#624]
### Current Behavior

Portal dev is not loading up - https://portal.dev.demo.catena-x.net/
there is a syntax error in the console. But after adding /home to the end, contents are loaded up.

### Expected Behavior

base url should load home page automatically

**Comment by nidhigarg-bmw** [comment]
@manojava-gk @jjeroch Not reproducible in the current dev
