### ISSUE TITLE
Thousands of requests are sent when backend not available

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-frontend#632]
### Current Behavior

When backend isn't available, the app continuously sends thousands of requests:

![image](https://github.com/eclipse-tractusx/portal-frontend/assets/46191613/91f30e0f-d6d4-4020-a655-2c001d2e10d2)

![image](https://github.com/eclipse-tractusx/portal-frontend/assets/46191613/0af41ee2-7e06-403a-807b-cb418dad4635)

### Expected Behavior

Go to error page, do not continuously send thousand of requests

### Additional Information

Registration app does show the expected behavior

**Comment by oyo** [comment]
An infinite loading loop was introduced to Main.tsx with this commit:
https://github.com/eclipse-tractusx/portal-frontend/commit/f2a794b30daffbb2cfedc4bc342ed23eb313c826#diff-ab49c302551eb75a7b6f559b4ac4662f8ae84806793544d693737095788b0c75

Just verified the code before doesn't show this behavior. Backend errors are not handled properly.

**Comment by msinamci** [comment]
Meeting and commitment between @jjeroch @evegufy @oyo @nidhigarg-bmw are necessary - @nidhigarg-bmw will organize it

**Comment by nidhigarg-bmw** [comment]
@evegufy Need scenario from where I can get this loop sending thousands of requests

**Comment by evegufy** [comment]
I discussed reproduced the issue together with @nidhigarg-bmw in a call, with the current state of the release branch from 2.0.0 version (RC5), the behaviour has improved as the frontend doesn't send thousends of pointless requests anymore but it's still just responding with a blank page and not redirecting to the error page.

**Comment by evegufy** [comment]
The logic for redirecting to the error page (once that the redirect works again) is the following:

- if GET https://portal-backend.tx.test/api/registration/applications responds with an error the redirect to the following error page occurs:
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/46191613/22860bb6-8685-4ed5-b52c-93d7f5dcc296)

- if some other the backend api(for instance GET https://portal-backend.tx.test/api/notification/count-details) responds with an error, it does not result in an redirect to the error page

@nidhigarg-bmw could you please confirm?

**Comment by nidhigarg-bmw** [comment]
@evegufy Yes, it worked in the same way as mentioned

**Comment by jjeroch** [comment]
@nidhigarg-bmw  & @evegufy 
Thanks. Happy to hear that this is not a default behavior now.
For the 500error of the endpoint following error page is expected:
https://eclipse-tractusx.github.io/portal-shared-components/?path=/story/errorpage--error-page&args=homeButtonTitle:


@nidhigarg-bmw is our error implementation still correctly working? Means single API errors are supported with pop-up-notifications as well as the in-page errors?

**Comment by nidhigarg-bmw** [comment]
@evegufy @jjeroch The Error page will look like this
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/101316912/d2235322-d44d-4923-a53d-135af917f028)
And this page will only work if backend isnt available. And it wont affect other error handlings and functionalities which are working before.
