### ISSUE TITLE
Company Certificate Deletion Error

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#659]
Defect found in version: **v1.7.0**

Env.: INT
User: CX Operator

**Action**
Accessed "Company Certificate" page and tried to delete my own certificate (see certificate in the screenshot below)

![Image](https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/d3dc9180-6802-4504-889c-9342cae4465f)

Deletion was running on a 404 error and following screen got displayed to the user:
![Image](https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/32dd3d74-4b36-4401-b27f-93e55860105e)

<br>

**Expected behavior:**
Instead of displaying an "Confirm" button, it should be called "Try Again" with re-triggering the endpoint.
Please check once if we have an icon for the unsuccess overlay. Per my knowledge we have a own style for the unsuccess overlay where an red icon is displayed. Please check once with in the user management implementation

**Comment by manojava-gk** [comment]
<img width="1054" alt="Screenshot 2024-04-01 at 2 54 20 PM" src="https://github.com/eclipse-tractusx/portal-frontend/assets/111366021/d817c834-929e-4381-b780-69c1aa4f21c1">
