### ISSUE TITLE
Frontend Input Field "URL" - Pattern Validation & Synchronisation with BE

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#672]
`Note this task need to get jointly approached with the BE team to ensure a satisfying system behavior`

#### Description (NOTE THIS IS THE BACKEND DESCRIPTION - FE to align with BE developer on the exact implementation - Decision to be documented inside the tickets)
Validate the urls being passed and omit those that use a different protocol than https, contain query or fragment or navigational elements (like '../..') in the path

Also make sure that the application does convert "dangerous" characters into safe equivalents (HTML entities or Unicode characters)

Examples of dangerous characters:
< >
Introduction of HTML or JavaScript code tags
' " &
Manipulating the content of SQL queries
{ } $ %
Embedding executable code in HTML server templates

Additionally, look into restricting the number of files that can be uploaded by the user.

---

Linked backend ticket: https://github.com/eclipse-tractusx/portal-backend/issues/587

**Comment by JordanGerada3** [comment]
I would like to pick up this topic. @typecastcloud

**Comment by MaximilianHauer** [comment]
based on discussion wiht @oyo  and @Phil91  we dont need this as html/sql syntax will not be executed due to frontend configuration
