### ISSUE TITLE
Element: Scroll Up Botton

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#675]
#### Summary
Implement a 'Scroll Up' button that appears on the bottom right of the screen when the user scrolls down the page. This button should allow users to quickly return to the top of the page with a single click.

#### Acceptance Criteria:
1. **Visibility Trigger:**
   - The 'Scroll Up' button should only become visible when the user scrolls down a predefined distance from the top of the page. (Action Item Developer: please check which possibilities we have to define the distance. Afterwards distance will be defined)

2. **Positioning and Design:**
   - Position the button on the bottom right of the viewport, ensuring it does not interfere with other interactive elements.
   - The button should have a design that is consistent with the application's style guide and should be clearly visible against the background content.

3. **Smooth Scrolling:**
   - Clicking the 'Scroll Up' button should result in a smooth scrolling animation that takes the user back to the top of the page.

4. **Responsiveness:**
   - The button should be responsive and work across different screen sizes and devices without obscuring content or other UI elements.

---

Note: make sure that the current implemented scroll up buttons are removed with this implementation => likely those are currently part of the footer of the pages.

---

Acceptance Criterias:

- [ ] Implement the change in the frontend application
- [ ] add the element in shared-components and add the element definition in storybook as well

Out of scope:

- [ ] registration app

**Comment by evegufy** [comment]
@manojava-gk @oyo PR https://github.com/eclipse-tractusx/portal-frontend/pull/868 was merged into the dev branch, even tough the issue https://github.com/eclipse-tractusx/portal-frontend/issues/675 is marked for the 2.1.0 release, please fix that
