### ISSUE TITLE
Harmonization and Standardization of Page Headers

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#676]
**Summary:**
The portal page headers need to be harmonized and standardized to ensure consistency and improve the overall user experience. The following rules should be followed for the headers:

#### Left-Aligned Header Titles
1. All header titles that are left-aligned should remain left-aligned.
2. The breadcrumb should be removed from all left-aligned headers.
3. All left-aligned headers should start at the same position on the page, using the same grid.
4. All left-aligned headers should have the same header size.

#### Central-Aligned Header Titles

1. All header titles that are central-aligned should remain central-aligned.
2. The breadcrumb should be removed.
3. The header title size should always be the same.

**Additional Information:**
Please ensure that the changes are thoroughly tested and do not affect the functionality or responsiveness of the website.

**Comment by MaximilianHauer** [comment]
approved
