### ISSUE TITLE
Update administration app roles api's

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/portal-frontend#686]
### Current Behavior

App roles aren't shown and can't get updated

### Expected Behavior

App roles are shown and can get updated

### Additional information

Bug available in dev branch

Due to change of backend api's:

GET: from /api/administration/user/app/{appId}}/roles to /api/administration/user/owncompany/roles/apps/{appId}

PUT: /api/administration/user/app/{appId}/roles to /api/administration/user/owncompany/users/{companyUserId}/apps/{appId}/roles

https://github.com/eclipse-tractusx/portal-frontend/blob/dev/src/features/admin/appuserApiSlice.ts#L80
https://github.com/eclipse-tractusx/portal-frontend/blob/dev/src/features/admin/appuserApiSlice.ts#L104
https://github.com/eclipse-tractusx/portal-frontend/blob/dev/src/features/appManagement/apiSlice.ts#L307

**Comment by lavanya-bmw** [comment]
@evegufy BE bug ticket for GET API: https://github.com/eclipse-tractusx/portal-backend/issues/575

**Comment by jjeroch** [comment]
@lavanya-bmw for the function
"User Management" assign "App Role(s)"
please use the following endpoint: `GET /api/administration/user/owncompany/roles/apps/{appId}` when calling the page to display the roles inside the page itself as well as inside the overlay when clicking on "+ Add Role"

Page: /appusermanagement/{appID}
