### ISSUE TITLE
App Marketplace: Category View Pagination

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#688]
**Issue Description:**
Currently, in the app marketplace, the "category view" displays the apps per category. If more than 4 apps exist for a category, a "more" button is displayed. When the user selects the "more" button, 4 additional apps are displayed. This means that if there are 12 apps for a category, the "more" button needs to be clicked twice. This functionality needs to be improved.

**Expected Behavior:**
1. When the user clicks on the "more" button, all the apps for the category should be displayed, instead of just 4 additional apps.
2. The "more" button should switch to a "collapse" button, indicating that the category apps are expanded.
3. If the user clicks on the "collapse" button, the category apps should be collapsed, and the "collapse" button should switch back to a "more" button.

**Steps to Reproduce:**
1. Navigate to the app marketplace.
2. Select a category with more than 4 apps.
3. Observe that a "more" button is displayed.
4. Click on the "more" button.
5. Observe that only 4 additional apps are displayed.
6. Click on the "more" button again.
7. Observe that the remaining apps for the category are displayed.

**Current Behavior:**
The "more" button in the "category view" only displays 4 additional apps when clicked, requiring multiple clicks to view all the apps for a category.

**Desired Outcome:**
The "category view" pagination should be improved to display all the apps for a category when the user clicks on the "more" button. The button should also switch to a "collapse" button when the category apps are expanded, and switch back to a "more" button when the category apps are collapsed.

**Comment by lavanya-bmw** [comment]
@jjeroch When the available apps are less than or equal to 4, then 'More' button is displayed and it is disabled too.
