### ISSUE TITLE
Sticky Sub-Menu Not Highlighting Current Section

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#690]
Detected in version **1.8.0**

**Issue Description:**
The sticky sub-menu is created to display to the user which section of the page they are currently in. Additionally, the user can easily switch to another section by clicking on available sub-chapters of the sub-navigation. After the user selects a section from the sub-menu, they are automatically directed to that section. However, when scrolling up and down to get to other sections, the previous selected sub-chapter is still highlighted in the sub-menu. This is unexpected behavior, as the sub-menu should always highlight the current displayed sub-chapter.

**Steps to Reproduce:**
1. Navigate to a page with a sticky sub-menu. (e.g. /companyrolesonboardingserviceprovider)
2. Select a sub-chapter from the sub-menu.
3. Observe that the selected sub-chapter is highlighted in the sub-menu.
4. Scroll up or down to a different section of the page.
5. Observe that the previously selected sub-chapter is still highlighted in the sub-menu, even though it is not the current section.

**Current Behavior:**
The sticky sub-menu is not highlighting the current section when scrolling up or down the page, instead, it is still highlighting the previously selected sub-chapter.

**Expected Behavior:**
The sticky sub-menu should always highlight the current section of the page, regardless of whether the user has previously selected a different sub-chapter from the sub-menu.

**Proposed Solution:**
Update the sub-menu logic to always highlight the current section of the page, regardless of whether the user has previously selected a different sub-chapter from the sub-menu. This can be achieved by detecting the current section of the page and updating the sub-menu accordingly.

---

Example Screenshots:

<img width="640" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/0d8388ce-717b-4f3d-88e2-90ff4e6018e8">

<img width="623" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/f7a958c0-037f-4cda-8e1f-bf4ac94bdea2">

**Comment by manojava-gk** [comment]
@jjeroch Highlighting selected button is not a feature, instead it is hover/focus effect which is default button behaviour. Now this is disabled.
