### ISSUE TITLE
Vite HMR not working

### ISSUE THREAD

**Issue by oyo** [eclipse-tractusx/portal-frontend#695]
### Current Behavior
After framework upgrade the development server doesn't reload and show changes after file editing.

### Expected Behavior
In development mode when a file is saved we expect to see the changes in the browser a few seconds after saving. Vite supports hot module replacement and it's working in small example projects.

### Steps To Reproduce
Example:
- Start the development server with `yarn start`
- Open the home page at http://localhost:3000/
- Open the source code for the home page: https://github.com/eclipse-tractusx/portal-frontend/blob/main/src/components/pages/Home/index.tsx
- Delete a section and save the file
- Check the browser if the content has been removed automatically
- If it doesn't you reproduced the bug. Reload the page to see your changes in action.

**Comment by charmi-v** [comment]
This issue appears to be related to Vite. 
There are two potential solutions:
1. Downgrade to Vite version 4.5.2.
2. Manually prevent full page reloads by adding a listener to vite:beforeFullReload. However, this approach has a limitation.

It's important to note that the second solution doesn't work with Vite version 5.2.13, which is currently used in the repository. For more details, refer to the related GitHub issues: [Issue 5763](https://github.com/vitejs/vite/issues/5763#issuecomment-1941966169) and [Issue 17447](https://github.com/vitejs/vite/issues/17447).

**Comment by MaximilianHauer** [comment]
@oyo  would propose the downgrade as it seems to be a less impactfull decision . sadly it seems that even the newest version 5.4.3  does not provide a fix.
