### ISSUE TITLE
Inconsistent page names

### ISSUE THREAD

**Issue by oyo** [eclipse-tractusx/portal-frontend#696]
### Current Behavior
Longer page names follow inconsistent naming conventions:
- no separation: https://portal.dev.demo.catena-x.net/companyrolesonboardingserviceprovider
- kebap-case: https://portal.dev.demo.catena-x.net/usecase-participation
- snake_case: https://portal.dev.demo.catena-x.net/appreleaseprocess_form
- camelCase: https://portal.dev.demo.catena-x.net/companyCertificate

### Expected Behavior
Page names should follow a consistent naming convention

### Steps To Reproduce
Open the definitions of the page names:
https://github.com/eclipse-tractusx/portal-frontend/blob/main/src/types/Constants.ts#L25-L107
Check the name values - also some constant keys are inconsinstent like: APPRELEASEPROCESS and APP_RELEASE_PROCESS_FORM

**Comment by evegufy** [comment]
@manojava-gk @oyo this issue is in status in review, why are no pull requests linked?

**Comment by manojava-gk** [comment]
> @manojava-gk @oyo this issue is in status in review, why are no pull requests linked?

Its already merged

<img width="782" alt="image" src="https://github.com/user-attachments/assets/ef51e2d8-544f-417d-88ee-089e595f8e20">

**Comment by MaximilianHauer** [comment]
following link is not adjusted: 
https://portal.int.catena-x.net/semantichub

**Comment by typecastcloud** [comment]
Hi @evegufy, are you already considering changes in helm values for PR eclipse-tractusx/portal-frontend#895 ?

Most camel case changes do not make a difference but something like consent_osp -> consentOsp is breaking the OSP path.
