### ISSUE TITLE
Use of MUI component instead of shared component

### ISSUE THREAD

**Issue by oyo** [eclipse-tractusx/portal-frontend#697]
### Current Behavior
Some times code uses MUI components directly where better alternatives exist.

### Expected Behavior
We created the Shared Components to simplify development and preconfigure MUI components for our style. They should be used whenever possible.

### Steps To Reproduce
Example:
https://github.com/eclipse-tractusx/portal-frontend/blob/main/src/components/overlays/AddMultipleUser/index.tsx#L25
Typography exists in the shared components

**Comment by jjeroch** [comment]
@manojava-gk could you please verify this once and adjust the implementation where needed
