### ISSUE TITLE
Company Subscription Page - Overlay "Unsubscribe" Text Values missing

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#714]
Detected in version **1.9.0 RC1**

All the text values are destroyed inside the "Company Subscription" => "Unsubscribe" Overlay :
<img width="1193" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/cd407283-665e-479b-acfd-a92d4ce97b83">

**Comment by lavanya-bmw** [comment]
The translations from main.json were removed in this PR: https://github.com/eclipse-tractusx/portal-frontend/pull/683
