### ISSUE TITLE
Update Overlay Styling for Connector Configuration**

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#743]
### Scope:
The scope of this ticket is to update the overlay styling for the Connector Configuration overlay in accordance with the provided design.
Additionally a couple of new fields is getting added and can get copied to the clipboard of the user.

**Page**: `/technicalsetup` (current name as part of v.2.0.0-RC4)

<img width="468" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/e18e02a4-be55-4577-99bc-42b0db7222ce">

**Description:**
The Connector Configuration overlay currently lacks consistency and does not align with the desired design. This ticket aims to update the overlay styling to ensure a visually appealing and consistent user experience.

**Tasks:**
1. **Review Design Guidelines:**
   - Review the provided design (see screenshot above) for the Connector Configuration overlay.

3. **Add new field and fetch content via the API response**
   - add the new fields (as per the design image)
   - fetch the field content via the endpoint provided
     - "trusted_issuer"
     - "participant_id"
     - "iatp_id"
     - "did_resolver"

3. **Update Overlay Implementation of the "Connector Configuration" overlay:**
   - Modify the existing overlay styles for the Connector Configuration overlay to match the provided design.
   - Ensure that the updated styling is responsive and compatible with different screen sizes.
   - Make sure that following fields get a copy icon which the user can click to save the value inside the clipboard
     - trusted issuer
     - token url
     - dimURL
     - participantID
     - iatp id
     - did resolver url

---

Text Values for the overlay sections (in "en") can get copied from the design board inside figma: https://www.figma.com/file/pcHZWXTQJUguIT75QSk9KW/Portal-Designs?type=design&node-id=10327-9900&mode=design&t=2mu2Fet57i8ZYT4z-0

**Comment by lavanya-bmw** [comment]
This ticket has the below changes too:
  - Added links on click of 'learn more' for 'Identity Provider Config' 
  - added copy functionality for horizontal static table in shared components
