### ISSUE TITLE
Technical user dropdown in connector registration overlay not handling pagination

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#752]
**Summary:**
There is a bug in the connector registration overlay where the dropdown field for the technical user is not handling pagination correctly. The dropdown is supposed to display the technical user received via the `GET /serviceaccounts` endpoint. However, since the endpoint includes pagination, the frontend is currently not able to handle it, resulting in incomplete or missing options in the dropdown.

To fix this bug, we need to update the frontend to properly handle pagination for the technical user dropdown in the connector registration overlay. This will ensure that all available technical users are displayed correctly in the dropdown, regardless of the number of pages returned by the `GET /serviceaccounts` endpoint.

**Steps to Reproduce:**
1. Open the connector registration overlay.
2. Look for the technical user dropdown field.
3. Observe that the dropdown does not display all available technical users.

**Expected Result:** The technical user dropdown should display all available technical users.

**Proposed Solution:**
1. Update the frontend code to handle pagination for the technical user dropdown.
2. Modify the dropdown logic to fetch and display all technical users from all pages returned by the `GET /serviceaccounts` endpoint.
3. Ensure that the dropdown presents all available technical users to the user for selection.

**Comment by manojava-gk** [comment]
Getting 404 even for the new url also
Request URL: 
https://portal-backend-rc.dev.demo.catena-x.net/api/registration/application/55c0c155-d91e-4a2c-8a53-09d53202a92b/declineregistration

Request Method: 
POST

Status Code: 
404
