### ISSUE TITLE
Missing Delete Option for newly created "Managed IdPs"

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#757]
Detected in version **2.0.0**

**Issue Description:**
When attempting to delete newly created "managed" IDPs, the action function is missing, preventing the deletion process from being completed successfully.

<img width="895" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/78b79fc0-9c3e-450a-9ea5-f53d3a27f6a2">

<br>
<br>

**Steps to Reproduce:**
1. Create a new "managed" IDP in the system.
2. Navigate to the IDP management section.
3. Locate the newly created IDP that needs to be deleted.
4. Click on the delete button or select the delete option from the context menu.

**Expected Result:**
The system should display the Action "Delete" and execute the deletion process for the selected "managed" IDP if selected by the user.

**Actual Result:**
The Action "Delete" is not available.

**Additional Information:**
- This issue is specific to newly created "managed" IDPs.
- Other types of IDPs (e.g., "own") can be deleted without any issues.
- The absence of the action function prevents the deletion process from being initiated.

**Comment by jjeroch** [comment]
@lavanya-bmw  in case you want to run through some live checks, please contact Danai

**Comment by lavanya-bmw** [comment]
@jjeroch  As per https://github.com/eclipse-tractusx/portal-frontend/issues/489, "Delete" is only available and possible if the IdP is in a disabled state. PFA where idp71 is disabled and 'delete' is available 
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/106523828/7a0079df-ea25-4385-919d-5248ef86ebfa)

**Comment by lavanya-bmw** [comment]
@jjeroch  As discussed, added delete option for newly created "Managed IdPs" when managed Idp has below values:
clientId is null and hasClientSecret is false.
