### ISSUE TITLE
Connector Config Details - missing error handling on API call /companyData/decentralidentity/urls

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#758]
Detected in version: 2.0.0 RC4

**Related Tickets:** [Follow up ticket of #674 & #643 & #683](https://github.com/eclipse-tractusx/portal-backend/issues/710)

**Description:**
The connector configuration frontend element/implementation does not handle API errors properly, resulting in a poor user experience. We need to make adjustments to the frontend section to handle API errors gracefully and ensure that customers are informed about any errors that occur.

The current lack of error handling in the frontend can lead to confusion and frustration for customers. Without proper notification of API errors, customers may not be aware of issues and may continue to interact with the application without realizing that their actions were unsuccessful. This can result in data inconsistencies and a poor user experience.

**Page**: `/technicalsetup`
**Function**: Connector Configuration

**Expected Behavior:**
When an API error occurs (401, 403, 409, 500, etc...), the frontend should handle it appropriately and inform the customer about the error. This can be achieved by displaying an error message or notification on the UI, providing clear and concise information about the error.

**Comment by manojava-gk** [comment]
<img width="1231" alt="Screenshot 2024-07-03 at 2 43 48 PM" src="https://github.com/eclipse-tractusx/portal-frontend/assets/111366021/27ccf3bd-3447-4db6-a86d-b1090f95f8c4">
<img width="1264" alt="Screenshot 2024-07-03 at 2 43 28 PM" src="https://github.com/eclipse-tractusx/portal-frontend/assets/111366021/55ca6d79-3085-4823-b372-318f9d0b14ba">
Error component with try again is for 500 status code.
