### ISSUE TITLE
Enhancement for Credential Request Page

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#773]
## Description
This ticket is created to address the enhancement of the credential request page on the Catena-X portal. The goal is to support loading and API errors for a better user experience.

## Details
- Page URL: [https://portal.{env}.demo.catena-x.net/usecase-participation](https://portal.{env}.demo.catena-x.net/usecase-participation)
- Current Behavior: The credential request page does not handle loading and API errors gracefully.
- Desired Behavior: Enhance the page to display loading indicators (page and elements) and provide error messages when API calls fail.

## Tasks
1. Implement loading indicators to provide visual feedback to the user while waiting for API responses. (GET and POST calls)
2. Handle API errors and display appropriate error messages to the user.
3. Test the enhanced page to ensure smooth loading and error handling.
4. Deploy the changes to the production environment.

**Comment by nidhigarg-bmw** [comment]
@jjeroch All API's (Download document, approve/decline, Revoke) in this page handling errors and giving error notification if there is any error from API response. 
For fetching credentials in /issuer call, if there is any error then its handling in the table itself.
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/101316912/b26af855-d5dc-4d3f-a165-a6eaac8ccf59)

Does it fine to you ?
