### ISSUE TITLE
Technical User Creation - API Response

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#788]
**Description:**
The backend response of POST /api/administration/serviceaccount/owncompany/serviceaccounts will change to an array. The frontend needs to be prepared to handle multiple service account responses. The overlay where the tech user is displayed needs to be enhanced to display multiple technical users if they are included in the response.

**Tasks:**
1. Update the frontend API request for POST /api/administration/serviceaccount/owncompany/serviceaccounts to handle the new backend response as an array.
2. Review the existing overlay component where the tech user is displayed.
3. Update the overlay to display multiple technical users if they are included in the backend response.
4. Ensure that the frontend can handle the new backend response correctly and update the user interface accordingly.

**Acceptance Criteria:**
- The frontend API request for POST /api/administration/serviceaccount/owncompany/serviceaccounts handles the new backend response as an array.
- The overlay for displaying the tech user is updated to display multiple technical users if they are included in the backend response.
- The frontend can handle the new backend response correctly and the user interface is updated appropriately.

----

Impacted Function:
**Page**: /technicaluser

**Comment by nidhigarg-bmw** [comment]
@jjeroch Made the changes and now getting always one user in POST API response
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/101316912/d380fe7c-e6e7-4ef5-87bf-0b2c5189dff8)
If gets multiple users, then again same thing will get repeat. Please see attached for an idea
![image](https://github.com/eclipse-tractusx/portal-frontend/assets/101316912/a83b6a8e-52f8-4ce3-bbc4-1bc2747b724f)
Does this make sense ?

**Comment by jjeroch** [comment]
yes that makes sense. Thanks. I am taking this solution :)
