### ISSUE TITLE
Enhance Readme file with Frontend Coding Guidelines

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#854]
**Description:**
The goal of this ticket is to enhance the project's README file by adding the frontend coding guidelines. This will include the following:

1. Usage of the shared-component-library for design elements
2. Implementation of text values via the locale files (de/en)
3. Consistency of file and folder naming
4. Any other relevant frontend coding best practices to be documented (please check carefully which guidelines we wanna share)

**Tasks:**
1. Review the current README file and identify the sections that need to be updated with the frontend coding guidelines.
2. Document the usage of the shared-component-library for design elements. This should include:
   - How to import and use the shared components
   - Naming conventions for custom components
   - Guidelines for consistent styling and theming
3. Describe the approach for implementing text values via the locale files (de/en). This should cover:
   - Folder structure for locale files
   - Naming conventions for locale keys
   - How to access and use the locale values in the codebase
4. Identify and document any other relevant frontend coding best practices that should be followed, such as:
   - Consistency of file and folder naming
   - Code formatting and linting
   - Handling of API responses and error states
   - Consistent use of state management patterns
5. Update the README file with the new frontend coding guidelines section.
6. Review the changes and ensure the guidelines are clear and comprehensive.
7. Commit the changes to the repository.

**Comment by manojava-gk** [comment]
## Coding guidelines

### Naming conventions for custom components

Folder, File and component name to be in Camel Case\
Scss files to be in Camel Case\
RTK folders and files to be in small case

### Import Components

Always use components from [portal-shared-components library](https://github.com/eclipse-tractusx/portal-shared-components)\
Do not import components directly from mui

### Allowed imports from mui

Box, useMediaQuery

### Guidelines for consistent styling and theming

Do not use useTheme from mui\
Use theme from the [portal-shared-components library](https://github.com/eclipse-tractusx/portal-shared-components)\
Use custom class names to override default or mui styles\
Use appropriate `Typography` for the text and do not override font family of it


### Create new text locale file

Create a new file in the respective `language` folder with the module name in `assets/locales`\
Use small cases for the `json` file\

ex: notifications.json

### Add new text values in locale file

Keys inside `json` file should be in Camel Case\

ex: notificationTitle

### Read text values from locale file

Import `useTranslation` from `react-i18next`\
Declare translation object using the specific module\

```
const { t } = useTranslation('notification')
```

Empty in the usetransation() will pull the data from `main.json` file

```
const { t } = useTranslation()
```

Usage ex:

```
t('header.title')
```

### Code formatting and linting

Before committing your changes,

1. Do run `yarn pretty` to format the code
2. Remove all the disabled linter rules from `.eslintrc.json` and run `yarn lint` on your newly created file or folder to see the results
3. Disable linter rules is allowd only for the exceptional cases. Code comments with proper reason is mandatory

### Handling of API responses and error states

1. All the api call has to be addressed with a throbber in the UI
2. Empty response to be shown with a proper message to the user
3. API error has to be shown in a component with appropriate action\
   a. Error code 4xx needs to show error component with message\
   b. Error code 5xx should allow user to refetch the api once again.

### State Managment

URL path names to be in Camel Case\

**Comment by manojava-gk** [comment]
@oyo awaiting your feedback on the above guidelines
