### ISSUE TITLE
Change role requirement for "My Organization" view

### ISSUE THREAD

**Issue by typecastcloud** [eclipse-tractusx/portal-frontend#856]
### Description

As portal user I want access to "My Organization" view when I have the corresponding role to access API for own company data [/administration/companydata/ownCompanyDetails](https://github.com/eclipse-tractusx/portal-backend/blob/73e24a69521f7ef757985328520b54c0c6649c71/src/administration/Administration.Service/Controllers/CompanyDataController.cs#L55-L69)

Currently required role for endpoint:
```
client: Cl2-CX-Portal
role: view_company_data
```
Currently required role for My Organization view:
```
client: Cl2-CX-Portal
role: view_partner_network
```

Goal: Matching roles for BE endpoint/FE page

### Acceptance Criteria

- [ ] [With user role Cl2-CX-Portal: view_company_data I can access My Organization page and view my own company data]

**Comment by jjeroch** [comment]
Looks good
Lets merge this against our 2.1.0 branch

**Comment by typecastcloud** [comment]
> Looks good Lets merge this against our 2.1.0 branch

There is no 2.1.0 branch. PR is based on dev -> trying to merge into dev.

**Comment by typecastcloud** [comment]
Issue is resolved by merged PR
