### ISSUE TITLE
sig#810: Company Data Management UI with Advanced Error Handling

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#888]
### Description:
Enhancement of the existing Company Data Management User Interface required, to improve the user experience by handling various error scenarios more gracefully. The frontend component should be able to detect and properly handle the following error responses from the API:

1. **Empty API Response** - When the API returns an empty dataset (including an empty pagination section), the UI should inform the user that no data is available instead of displaying a blank page or a broken component. `//NOTE - use the same implementation as for the connector page/table`

Example for **Empty API Response**
```json
{totalElements: 0, totalPages: 0, page: 0, contentSize: 0, content: []}
```

2. **API Response 401 Error (Unauthorized)** - Upon receiving a 401 error, the UI should prompt the user the info that the API load was unsuccessful

  <img width="396" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/0de6efac-981e-4b5f-9d51-a98a5cb03afb">

3. **API Response 403 Error (Forbidden)** - If a 403 error is encountered, the UI should prompt the user the info that the API load was unsuccessful due to missing permission. Example design see below - NOTE: dont provide a reload

  <img width="396" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/dd039d91-edcd-4007-bd74-ff875c99d1f1">

4. **API Response 50x Errors (Server Errors)** - The UI should handle server-side errors by displaying a user-friendly message that an error has occurred and offer to retry the request or return to a previous stable state.

   - Implement a catch-all error handler for all 50x server errors to display a generic "Something went wrong" message.
   - Provide the user with the option to retry the action that caused the error or to report the issue.

 <img width="410" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/815b44fb-7eaf-46ac-80b5-ae5b05b326a3">

<br>
<br>

## Reference As-Is

<img width="771" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/2308a480-13be-41c2-a208-36714abc9a2c">

**Comment by manojava-gk** [comment]
I have extended the feature which is already present in PageLoadingTable component to the Table component. Based on the response status table will show up appropriate error component

**Comment by evegufy** [comment]
I suggest to close this issue
