### ISSUE TITLE
Usability: update registration admin board centralization and sizing

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#897]
### Description
Minor improvements for `/applicationrequests` page.
<br>

**1st: Update Status button status sizing**
Update the sizing of the status from 16px to 14px
<img width="108" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/1f6d2f9b-4230-43cb-b766-d9ccf517e587">
<br>

**2nd: Content table location**
Ensure that the table content is vertical central located (see image below)

<img width="748" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/0725cbe0-bac3-420c-ac81-03f6fac55de6">
<br>
<br>
<br>

**3rd: Table header**
Update the table header title
- update header title of the table from "Company Application Info" to "Company"
<br>

**4th: Sizing content documents inside overlay**
Inside the company details overlay (when clicking on "Details") the sizing of the info message "no documents available" under the document section is far to huge. Its using 18px while only 14px should be used.
<img width="274" alt="image" src="https://github.com/eclipse-tractusx/portal-frontend/assets/94133633/04a7918a-6cfe-4b13-90aa-553d5b2668fa">
<br>

**Comment by lavanya-bmw** [comment]
@jjeroch Inside details overlay, added 'No roles available' info when roles are empty.
