### ISSUE TITLE
Error accessing "/registration/external" and "/?overlay=consent_osp" – Page Not Existing

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#907]
**Description:** Users are unable to access the external customer registration and consent overlay pages. Upon attempting to navigate to "/registration/external" or "/?overlay=consent_osp", an error stating "Page not existing" is displayed. This issue has arisen subsequent to the UI update performed in pull request [#547](https://github.com/eclipse-tractusx/portal-frontend/pull/547). The pages were previously implemented and functional as per ticket [#468](https://github.com/eclipse-tractusx/portal-frontend/issues/468).

**Reproduction Steps:**
1. Navigate to "/registration/external"
2. Observe the "Page not existing" error
3. Navigate to "/?overlay=consent_osp"
4. Observe the same error message

**Expected Behavior:** The user should be redirected to the appropriate registration or consent overlay page based on their customer type.

**Actual Behavior:** The user receives an error message indicating that the page does not exist.

**Customer Attributes:**
- `applicationStatus`: "CREATED"
- `applicationType`: "EXTERNAL"

**Additional Information:**
- The issue needs to be validated to determine under what URL or conditions the page is meant to be reachable.
- This bug is likely to affect external customer onboarding experience and needs immediate attention.

`NOTE: I have an example test user if needed. Only selected users are able to access this function`

**Comment by jjeroch** [comment]
Issue identified on INT - please check once which version is released to INT to analyse the correct code version

**Comment by oyo** [comment]
@jjeroch is the test user in our keepass? which one is it? or send me the credentials please

**Comment by typecastcloud** [comment]
Hi @evegufy @jjeroch @oyo,

in /portal repo the configuration for externalRegistrationPath is still set to /?overlay=consent_osp. This will result in broken links in e-mails afaik. Please confirm.

https://github.com/eclipse-tractusx/portal/blob/1eb1ad35c0b3996e76dc2394c7d54743e3f9eba4/charts/portal/values.yaml#L870

**Comment by evegufy** [comment]
> Hi @evegufy @jjeroch @oyo,
> 
> in /portal repo the configuration for externalRegistrationPath is still set to /?overlay=consent_osp. This will result in broken links in e-mails afaik. Please confirm/fix.
> 
> https://github.com/eclipse-tractusx/portal/blob/1eb1ad35c0b3996e76dc2394c7d54743e3f9eba4/charts/portal/values.yaml#L870

@typecastcloud , @oyo and I had a look and you're right, @oyo will raise a pr.
