### ISSUE TITLE
Application request company details overlay not showing uploaded document

### ISSUE THREAD

**Issue by JordanGerada3** [eclipse-tractusx/portal-frontend#915]
Description:
During registration process of a test company, a document was uploaded  in document upload step. After submission, portal admin has checked the application from the portal side, however the document is not available in overlay. Document information is visible in payload. 

Current Behaviour:
Inside of "Application Requests" page, when clicking on details of any company application, documents field shows "no data available" despite user uploading document during registration process. 

Expected Behaviour:
Portal Admin should see the uploaded document. 

Steps To Reproduce:

1. In portal business parter invite page, Invite a test company.
2. As the test company, following registration steps and upload a pdf (can be blank) and submit.
3. Login as a portal Admin.
4. Navigate to Application Requests.
5. Click on the details button of the test company.
6. Check to see if the document is viewable under "Document(s)".

![Screenshot 2024-07-10 at 17 28 34](https://github.com/eclipse-tractusx/portal-frontend/assets/138688996/92ed45de-c079-4eb8-8926-4a8b11abd42e)

![Screenshot 2024-07-10 at 17 29 37](https://github.com/eclipse-tractusx/portal-frontend/assets/138688996/46758e51-4e76-474c-9826-95d6d516fda3)

**Comment by MaximilianHauer** [comment]
@JordanGerada3 do you deliver the pr ?

**Comment by JordanGerada3** [comment]
> @JordanGerada3 do you deliver the pr ?

I currently do not have capacity to work on this issue.

**Comment by MaximilianHauer** [comment]
@JordanGerada3  i pushed it into the sprint if a frontender of us has capacity he will assign it to himself.

**Comment by MaximilianHauer** [comment]
@manojava-gk  will take over this topic

**Comment by manojava-gk** [comment]
@MaximilianHauer / @evegufy I need admin access to test or fix this issue. Could you pls enable or provide the necessary details?

**Comment by MaximilianHauer** [comment]
@manojava-gk  gave you company admin now you have all roles :O 
or do you mean cx-operator ? then schedule a short meeting with evelyn/phil/me/norbert/martin to screenshare

**Comment by MaximilianHauer** [comment]
will test it myself @gopalreddy-bmw

**Comment by MaximilianHauer** [comment]
tested
