### ISSUE TITLE
Implement Loading State for Provider Subscription Detail Overlay

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#922]
**Description:**
When accessing the provider subscription detail view and initiating the detail overlay (via the arrow button), the UI currently pre-fills data fields with "n/a" before the backend has completed fetching the data. This ticket aims to replace the premature "n/a" data indication with a loading element that better represents the system's state while awaiting data retrieval.

**URLs:**
- Provider Subscription Detail View:
  - [https://portal.dev.demo.catena-x.net/appSubscription](https://portal.dev.demo.catena-x.net/appSubscription)
  - [https://portal.dev.demo.catena-x.net/serviceSubscription](https://portal.dev.demo.catena-x.net/serviceSubscription)

**Tasks:**
1. Identify the component responsible for rendering the provider subscription detail overlay.
2. Replace the "n/a" placeholders with a loading element (to be used from the shared-component-library) within the overlay component.
3. Ensure the loading element persists until the API call to fetch the backend information is completed.
4. Upon successful data retrieval, the UI should transition smoothly from displaying the loading element to presenting the fetched data.
5. Test the implementation to ensure that the loading state is shown appropriately across different scenarios.

**Acceptance Criteria:**
- No "n/a" placeholders are visible when the detail overlay is opened while the data fetch from backend side are still under progress.
- A loading element is displayed while the API call is in progress.
- The fetched data replaces the loading element without any noticeable flicker or delay.
- The UI gracefully handles slow network conditions
- The implementation is consistent across both `appSubscription` and `serviceSubscription` detail views.
- The changes do not negatively impact other components or the overall performance of the system.

**Additional Notes:**
- The chosen loading element should match the design guidelines and aesthetics of the portal.

**Potential Risks:**
- Incomplete or improper handling of loading states may lead to suboptimal user experience or misrepresentation of the system's status.

**Out of scope:**
- error scenario

**Comment by MaximilianHauer** [comment]
approved
