### ISSUE TITLE
Service Manager User | Service Management -> Admin Board | 403 Forbidden

### ISSUE THREAD

**Issue by tfjanjua** [eclipse-tractusx/portal-frontend#936]
### Current Behavior
`Service Management` -> `Admin Board` page is not showing the Services and responding 403 Forbidden error.

### Expected Behavior
`Service Manager` should be able to see services list on `Admin Board` page OR `Service Manager` should not see `Admin Board` sub-menu option under `Service Management` menu if Service Manager doesn't supposed to have related permissions.

### Steps To Reproduce
- Login to the portal as a Service Manager
- Mouse Hover on Service Management menu and click on Admin Board option

### Findings
`Service Management` -> `Admin Board` page is calling the API: https://portal-backend.entry.cofinity-x.com/api/services/serviceRelease/inReview?size=15&page=0&status=InReview&sorting=DateDesc

and this API has following permissions: 

- approve_service_release
- decline_service_release

but `Service Manager` user account doesn’t have such permissions, I can share `Service Manager` user account’s access token and its existing list of permissions, if required.

**From frontend:**
I found that frontend is showing or hiding this Admin Board page on the basis of following roles:

- APPROVE_SERVICE_RELEASE = 'activate_subscription'
- DECLINE_SERVICE_RELEASE = 'decline_service_release'

So, the issue seems to be at the frontend side that `APPROVE_SERVICE_RELEASE` variable as wrong role value (`activate_subscription`) which needs to be corrected by `approve_service_release` value so, that this `Admin Board` page would only be visible to the users who would have same roles as API roles.

**Comment by tfjanjua** [comment]
This issue was created on backend with the assumption that this issue could be resolved from backend side but the issue needs to be resolved from the frontend side.
https://github.com/eclipse-tractusx/portal-backend/issues/831

**Comment by evegufy** [comment]
@tfjanjua thank you for analysing!

In general, it would be great if you could not link to closed systems like your entry "entry" environment, such an example link is much more friendly in the open: https://portal-backend.example.org/api/services/serviceRelease/inReview?size=15&page=0&status=InReview&sorting=DateDesc

**Comment by tfjanjua** [comment]
Closing this issue as related PR has been merged
