### ISSUE TITLE
Extend Subscription Management Detail Overlay

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#940]
## Description:
Extend the subscription management detail overlay provided for both the app and service provider pages (`/appsubscription` and `/servicesubscription`) by adding additional API response content.

### Current Implementation
<img width="696" alt="image" src="https://github.com/user-attachments/assets/6655b373-a9f0-44d7-b95d-0926ec7f4d68">

### Needed Change

With the implementation of https://github.com/eclipse-tractusx/portal-backend/issues/841 the endpoint `GET /api/apps/{appId}/subscription/{subscriptionId}/provider` got enhanced to include additional properties/attributes.

**Endpoint:** `GET /api/apps/{appId}/subscription/{subscriptionId}/provider`

**New Response body content:**
```
... 
 "externalService": {
    "trusted_issuer": "string",
    "participant_id": "string",
    "iatp_id": "string",
    "did_resolver": "string",
    "decentralIdentityManagementAuthUrl": "string",
    "decentralIdentityManagementServiceUrl": "string"
  }
}
```

Add this newly added content within the overlay. Make sure to validate the swagger documentation carefully to understand the nullable field values and to handle different endpoint responses.
If a value is not provided by the backend, show this respective value within the UI as "-"

---

#### Deutsch

| Key | FE-Label | Description (to be displayed if the user takes the hover on the questionmark icon) |
| --- | --- | --- |
| `trusted_issuer` | Vertrauenswürdiger Aussteller | Der vertrauenswürdige Aussteller, der für die Ausstellung der Identitätsnachweise verantwortlich ist. |
| `participant_id` | Teilnehmer-ID | Die eindeutige Kennung des Teilnehmers im externen System. |
| `iatp_id` | IATP-ID | Die eindeutige Kennung des IATP-Programms (Identity and Trust Protocol). |
| `did_resolver` | DID-Resolver | Die URL des DID-Resolvers (Decentralized Identifier), der für die Auflösung der dezentralen Identitäten verwendet wird. |
| `decentralIdentityManagementAuthUrl` | Auth-URL für dezentrales Identitätsmanagement | Die URL des Authentifizierungsendpunkts für das dezentrale Identitätsmanagement. |
| `decentralIdentityManagementServiceUrl` | Service-URL für dezentrales Identitätsmanagement | Die URL des Dienstendpunkts für das dezentrale Identitätsmanagement. |

#### English

| Key | FE Label | Description (to be displayed if the user takes the hover on the questionmark icon) |
| --- | --- | --- |
| `trusted_issuer` | Trusted Issuer | The trusted issuer responsible for issuing the identity credentials. |
| `participant_id` | Participant ID | The unique identifier of the participant in the external system. |
| `iatp_id` | IATP ID | The unique identifier of the IATP (Identity and Trust Protocol). |
| `did_resolver` | DID Resolver | The URL of the DID (Decentralized Identifier) resolver used for resolving decentralized identities. |
| `decentralIdentityManagementAuthUrl` | Decentralized Identity Management Auth URL | The URL of the authentication endpoint for the decentralized identity management. |
| `decentralIdentityManagementServiceUrl` | Decentralized Identity Management Service URL | The URL of the service endpoint for the decentralized identity management. |

**Comment by MaximilianHauer** [comment]
@jjeroch  what exactly needs to be added ?

**Comment by jjeroch** [comment]
> @jjeroch what exactly needs to be added ?

Details in the description. Ready for implementation. Design support needed. FE developer to align the UI with @MaximilianHauer

**Comment by shahmargi12** [comment]
Hi @MaximilianHauer 

I am interested in contributing to this task. 

Could you please help me with the UI so that I can start with the front-end implementation?

Thank you!

**Comment by gopalreddy-bmw** [comment]
@MaximilianHauer 
I have checked this user story, and it is working according to the requirements.

Attached Screenshots for references
![image](https://github.com/user-attachments/assets/d216a196-0b56-424e-bd56-6e2f075b6ebe)
![image](https://github.com/user-attachments/assets/ab622ab0-7e97-41b5-ab0b-42bacd5aafae)
