### ISSUE TITLE
sig#810: Enhancement of Company Data Management UI: Integration of Extended Error Handling for Sharing State

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#941]
### Ticket Title:
Enhancement of Company Data Management UI: Integration of Extended Error Handling for Sharing State

---

### Description:
We are aiming to improve the user experience of the Company Data Management interface by introducing a more comprehensive error handling mechanism. The enhancement involves integrating the GET /v6/sharing-state endpoint to the current UI workflow. This new feature will enable the UI to display whether the processing of company data that are in a "PENDING" state is still in progress or if there has been an error during the processing. The error detection will be facilitated by checking for specific response body attributes provided by the endpoint.

---

### Acceptance Criteria:
1. **Endpoint Integration:** Incorporate the GET /v6/sharing-state endpoint into the Company Data Management UI logic.
2. **Error Handling Logic:** Implement logic to detect and handle errors based on the response body attributes: "sharingStateType", "sharingErrorCode", and "sharingErrorMessage".
3. **UI Feedback:** Update the UI to provide feedback to the user when company data is in a "PENDING" state and to show appropriate error messages if the "SharingProcessError" is identified.
4. **Retry Mechanism:** Include a retry mechanism or guidance for the user to rectify the error if possible.
5. **Logging:** Ensure that all error states and the associated error messages are logged for further investigation and audit purposes.
6. **Documentation:** Update the technical documentation to reflect the new changes and error handling procedures.
7. **Testing:** Develop unit tests and integration tests to validate the new functionality and error handling logic.

---

### Technical Implementation Details:
- Call the GET /v6/sharing-state endpoint for company data with the "PENDING" status.
- Parse the response body for the attributes: "sharingStateType", "sharingErrorCode", and "sharingErrorMessage".
- Develop a new UI component or modify existing components to display the sharing state and error information.
- Implement a service layer to encapsulate the logic for error detection and handling.
- Design a user-friendly error message display, possibly with tooltips or a dedicated error information section.

---

### Dependencies:
- Ensure the backend service for the GET /v6/sharing-state endpoint is fully operational and accessible.

---

### Impact Assessment:
- The enhancement may require a brief downtime or maintenance window if the changes affect critical functionality.
- User training or communication may be necessary to inform about the new error handling features.

---

### Rollout Plan:
1. Develop and test the new features in a development environment.
2. Perform code reviews and iterate based on feedback.
3. Deploy to a staging environment for integration testing.
4. Conduct user acceptance testing (UAT) with a select group of users.
5. Plan and execute the deployment to production with appropriate change management processes.
6. Monitor the feature post-release for any unforeseen issues.

---

Please proceed with the implementation following the above specifications. Let's enhance our user experience and improve the robustness of our

**Comment by jjeroch** [comment]
In the scenario of an Error, the Status "Error" (in red) is supposed to get displayed, NOT "Pending". 
Additionally we need an solution to display the error well. to be identified how we might do this.

**Comment by manojava-gk** [comment]
<img width="880" alt="Screenshot 2024-07-22 at 11 10 21 PM" src="https://github.com/user-attachments/assets/cd789af4-e925-4bcd-b500-accdb33e9557">
<img width="933" alt="Screenshot 2024-07-22 at 11 10 12 PM" src="https://github.com/user-attachments/assets/aac06bf3-9885-4733-a59b-4e7f6f833710">

Initial design to show Error in listing page and in the detail page.
@jjeroch @MaximilianHauer

**Comment by manojava-gk** [comment]
@jjeroch @MaximilianHauer created a new site from portal successfully 
<img width="916" alt="Screenshot 2024-07-24 at 4 53 56 PM" src="https://github.com/user-attachments/assets/9a0b117e-c751-4fb3-ae53-d514557c3796">

**Comment by MaximilianHauer** [comment]
@manojava-gk  i assume we should limit the errormessage only to show the message part and not everything 
![image](https://github.com/user-attachments/assets/dbf8441a-3b21-45bb-ac65-2b59467ae900)

**Comment by manojava-gk** [comment]
> @manojava-gk
> 
> ### error message
> i assume we should limit the errormessage only to show the message part and not everything ![image](https://private-user-images.githubusercontent.com/168809208/361406538-dbf8441a-3b21-45bb-ac65-2b59467ae900.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDQxOTgsIm5iZiI6MTcyNTAwMzg5OCwicGF0aCI6Ii8xNjg4MDkyMDgvMzYxNDA2NTM4LWRiZjg0NDFhLTNiMjEtNDViYi1hYzY1LTJiNTk0NjdhZTkwMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNzQ0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zNGI5MzA4ODAyYzVjNTdjNzNiZDFiNWE0ZmMzZDZhOGQ5YzhiODU4ODMxZTVkMDIzZDQwNzkzZjQ0MTNmNmRlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.JWQWDFn6gnvL43eZhNXJj6sxU6P4ESe4NZjt_9xiMLo)
> 
> ### table header
> please add the following table header ![image](https://private-user-images.githubusercontent.com/168809208/361802741-fa506f47-ab2b-48da-b88f-4246a87992c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMDQxOTgsIm5iZiI6MTcyNTAwMzg5OCwicGF0aCI6Ii8xNjg4MDkyMDgvMzYxODAyNzQxLWZhNTA2ZjQ3LWFiMmItNDhkYS1iODhmLTQyNDZhODc5OTJjNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgzMFQwNzQ0NThaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOGQ2MmNkMGYwOTZjOTU2OWRjMWMyNzIyNjJhMjU1NTJjOTg3MjVmNGE4MmRlZGIxOGQwOWYzY2E4YjRkZDY4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dN4KUp8DNkkNmK1ydJ4I1PDI2VQFqqR7VVN6gXy1YBE)

As discussed, error message is coming from sharing-states api response. It is not handled from portal side.

Table header is updated

**Comment by evegufy** [comment]
Hi @manojava-gk with which PR did you update the table header? I don't see it linked.

**Comment by MaximilianHauer** [comment]
approved
