### ISSUE TITLE
sig#810: Company Data Management - Bulk load via CSV

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#942]
**refinement ongoing*

### 1. Download CSV Template File

Swagger Docu: https://business-partners.int.catena-x.net/companies/test-company/ui/swagger-ui/index.html#/partner-upload-controller/getPartnerCsvTemplate

**Endpoint:** `/v6/input/partner-upload-process`
**Method:** `GET`

**Refinement open**
- supported error scenarios
- what if I want to fetch my previous uploaded data?
- how to overwrite

<br>
<br>

### 2. Upload new CSV File

Swagger Docu: https://business-partners.int.catena-x.net/companies/test-company/ui/swagger-ui/index.html#/partner-upload-controller/uploadPartnerCsvFile

**Endpoint:** `/v6/input/partner-upload-process`
**Method:** `POST`

**Refinement open**
- supported error scenarios
-

**Comment by MaximilianHauer** [comment]
will be solved via 
* https://github.com/eclipse-tractusx/portal-frontend/issues/1026
* https://github.com/eclipse-tractusx/portal-frontend/issues/1027
