### ISSUE TITLE
sig#803: Add Technical User "Status" inside the technical user management page

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#944]
#### Description:
The Technical User Management page (https://portal.int.demo.catena-x.net/technicaluser) requires an enhancement to display the status of each technical user in the form of a chipcard, similar to what we have for normal users. The status value for each technical user is available through a GET API endpoint. The task involves fetching the status from the backend and implementing the visual chipcard indicator within the technical user table.

<img width="136" alt="image" src="https://github.com/user-attachments/assets/43abeca4-6cd4-4bea-b1bd-4b8bce54a723">

#### Pre-implementation Checklist:
- [ ] Review the current functionality of the Technical User Management page.
- [ ] Familiarize yourself with the API endpoint for fetching technical user statuses:
  - GET `/api/administration/serviceaccount/owncompany/serviceaccounts`
- [ ] Consult the API documentation to understand all available status tags:
  - API Documentation: https://portal-backend.dev.demo.catena-x.net/api/administration/swagger/index.html

#### Implementation Details:
- [ ] Fetch the status data for each technical user from the backend API; property `"status":`.
- [ ] Implement/intake the chipcard component of the `portal-shared-component registry` to visually represent the status of each technical user.
- [ ] Integrate the chipcard component into the technical user table on the Technical User Management page.
- [ ] Ensure that the chipcard's color-coding and text reflect the status accurately.
- [ ] Handle loading and error states appropriately within the UI.

#### Documentation:
- [ ] Update the Technical User Management page documentation to include the new status chipcard feature.
- [ ] Ensure that the component's integration is documented in the code with comments for clarity as well as inside storybook

#### Acceptance Criteria:
- [ ] The status chipcard is displayed for each technical user in the table on the Technical User Management page.
- [ ] The chipcard correctly reflects the status of the technical user as fetched from the backend API.
- [ ] The feature works correctly in various browsers and is responsive across different devices.

**Comment by jjeroch** [comment]
Please make sure to validate against the backend swagger docu which values are possible and make sure that an translation is existing

**Comment by MaximilianHauer** [comment]
@lavanya-bmw  i had a look please proceed as following:

ACTIVE = green (confirmed)
INACTIVE = red (declined)
PENDING = yelow (pending)
DELETED = grey (to be added to the styleguide)

**Comment by lavanya-bmw** [comment]
@jjeroch @MaximilianHauer Regarding documentation, need more information where to update the docs as https://portal.dev.demo.catena-x.net/documentation/?path=user%2F03.+User+Management%2F03.+Technical+User is currently empty

**Comment by lavanya-bmw** [comment]
> @lavanya-bmw i had a look please proceed as following:
> 
> ACTIVE = green (confirmed) INACTIVE = red (declined) PENDING = yelow (pending) DELETED = grey (to be added to the styleguide)

Shared component changes is available in PR: https://github.com/eclipse-tractusx/portal-shared-components/pull/249

**Comment by oyo** [comment]
> Shared component changes is available in PR: [eclipse-tractusx/portal-shared-components#249](https://github.com/eclipse-tractusx/portal-shared-components/pull/249)

@jjeroch @MaximilianHauer PR is approved from my side - please label PR with newly created tag "merge ready" if you consider this ready to merge

**Comment by MaximilianHauer** [comment]
> @jjeroch @MaximilianHauer Regarding documentation, need more information where to update the docs as https://portal.dev.demo.catena-x.net/documentation/?path=user%2F03.+User+Management%2F03.+Technical+User is currently empty
place to update document -> https://portal.int.catena-x.net/documentation/?path=user%2F03.+User+Management%2F03.+Technical+User%2F01.+Technical+User+Overview.md

* Screenshot needs to be updated ( ensure that no personal data is involved ) 
* Short description on existing status

**Comment by lavanya-bmw** [comment]
> > @jjeroch @MaximilianHauer Regarding documentation, need more information where to update the docs as https://portal.dev.demo.catena-x.net/documentation/?path=user%2F03.+User+Management%2F03.+Technical+User is currently empty
> 
> @lavanya-bmw i would ask you to update the following page https://portal.int.catena-x.net/documentation/?path=user%2F03.+User+Management%2F03.+Technical+User%2F01.+Technical+User+Overview.md
> 
> * Screenshot needs to be updated ( ensure that no personal data is involved )
> * overview of all status and their interpretation

PR link: https://github.com/eclipse-tractusx/portal-assets/pull/377

**Comment by MaximilianHauer** [comment]
approved
