### ISSUE TITLE
sig#796: Admin UI for Managing SD Document Retriggering

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#949]
`DRAFT ticket, details to be added as soon as backend is available`

## Ticket Description
The purpose of this ticket is to design and implement a Frontend (FE) User Interface that corresponds with the new backend features for managing SelfDescription (SD) documents. This interface will allow administrators to interact with the GET API endpoint and trigger the SD document creation job.
Linked backend ticket: https://github.com/eclipse-tractusx/portal-backend/issues/813

## Objectives

1. **Admin UI for GET API Endpoint**:
   - Develop a new section in the admin panel to display missing SD documents. (Location: user navigation - Clearinghouse Self-Description)
   - Implement UI components to show detailed information about missing SD documents, including total counts and lists of companies and connectors.
   - Integrate the UI with the new GET API endpoint ensuring data is retrieved and displayed correctly.
   - Add authentication and authorization mechanisms in the UI to ensure that only users with the 'approve_new_partner' permission can access this feature.

2. **Admin UI for Administrator-Triggered Job**:
   - Create a UI element (e.g., button) that allows administrators to trigger the SD creation job.
   - Implement feedback mechanisms in the UI to inform the administrator of the job's progress, completion, and any errors encountered.
   - Ensure the job trigger UI requires the 'approve_new_partner' permission.

## Acceptance Criteria

1. The Admin UI for the GET API endpoint must:
   - Display a list of all companies and connectors missing SD documents, including the total counts. `UI solution needed; object separated`
   - Be accessible only to users with the 'approve_new_partner' permission. `AI: permission to be rechecked`
   - Present clear, concise, and correct information about customer and company records. `UI solution needed`

2. The Admin UI for the administrator-triggered job must:
   - Allow only users with the 'approve_new_partner' permission to execute the job. `AI: permission to be rechecked`
   - Provide real-time feedback on the status of the SD creation process.
   - Record and display any initiation, completion, or failure of the SD creation process. `UI solution needed`

## Implementation Steps

1. Design the UI layout for the new admin section managing SD documents.
2. Develop UI components to list missing SD documents and display total counts.
3. Integrate the GET API endpoint with the UI to fetch and display the required data.
4. Implement authentication and authorization checks on the UI for the new features.
5. Design the UI component to trigger the SD creation job and display job status.
6. Handle state management and error handling in the UI for the new features.
7. Write and execute tests for the new UI components.
8. Update the admin panel documentation with the new features.
9. Conduct a review of the implemented UI with the team to gather feedback and make necessary adjustments.

---

### Wireframe

<img width="384" alt="image" src="https://github.com/user-attachments/assets/6d8f25e7-059f-4e6c-b8a5-9b8d6a5ef581">

---

#### Endpoints

**GET Connector Overview**

**Endpoints:** `/api/administration/connectors/missing-sd-document?page=0&size=15`
**Methods:** `GET`

**response json**
```
{
  "meta": {
    "totalElements": 0,
    "totalPages": 0,
    "page": 0,
    "contentSize": 0
  },
  "content": [
    {
      "connectorId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string",
      "companyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "companyName": "string"
    }
  ]
}
```

**GET Company Overview**

**Endpoints:** `/api/administration/companyData/missing-sd-document?page=0&size=15`
**Methods:** `GET`

**response json**
```
{
  "meta": {
    "totalElements": 0,
    "totalPages": 0,
    "page": 0,
    "contentSize": 0
  },
  "content": [
    {
      "companyId": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "name": "string"
    }
  ]
}
```

**Retrigger SD Creation**

**Company**

**Endpoints:** `/api/administration/companyData/trigger-self-description`
**Methods:** `POST`

**Connector**

**Endpoints:** `/api/administration/connectors/trigger-self-description`
**Methods:** `POST`

**Comment by MaximilianHauer** [comment]
endpoint details will be added as soon as backend ticket is finished. 
design can be started already

**Comment by MaximilianHauer** [comment]
as aligned topic wont be part of the inbetween release.
focus is still on 24.12

**Comment by kunalgaurav-bmw** [comment]
Hi Team, I need some confirmation over the following points, which require clarification:

- Is this UI components intended to appear as an overlay?
- Can please provide detailed information on the navigation path. 
- Will this be a completely new page under the User Menu? If yes, please confirm its exact position within the menu and the menu name to be used?

**Comment by MaximilianHauer** [comment]
1. Should be a new page called "Clearinghouse Self-Description"
2. Should be placed bellow "Application Requests"
3. Buttonname "Reprocess"
4. Compliance Status should be a toggle that is showing the state of the configuration in "backend -> processesworker -> clearinghouseConnectDisabled" if you cant find it ask @Phil91 
5. show a progress circle next to the button to show the overall procession of "overall amount of companies / processed companies " e.g. (10/5)

**Comment by oyo** [comment]
> 5. overall we should show the user that the progress is running i am uncertain what our best-practice is her @oyo please provide guidance for this. (process cyrcle that is updated? loading bar ? )

@kunalgaurav-bmw going to provide a branch with a rough sketch

**Comment by MaximilianHauer** [comment]
@oyo  / @kunalgaurav-bmw  is this clarified ? open questions ?

**Comment by MaximilianHauer** [comment]
@oyo / @kunalgaurav-bmw  i prepared a very bad mockup that gives an idea how we should restructure the design of this page 
lets discuss it on monday  
![image](https://github.com/user-attachments/assets/d7c4fd84-37ac-4685-af4a-986257db9515)

**Comment by MaximilianHauer** [comment]
need to disable the reprocess buttons as long as the configuration is disabled

**Comment by MaximilianHauer** [comment]
@gopalreddy-bmw  please have a look in the design and if the function works properly. @Phil91  can support you in testing the functionality

**Comment by MaximilianHauer** [comment]
will test it myself @gopalreddy-bmw
