### ISSUE TITLE
sig#803: user feedback deletion asynchron technical user

### ISSUE THREAD

**Issue by jjeroch** [eclipse-tractusx/portal-frontend#950]
`Refinement ongoing`

## Description:
In the current application flow a synchron user deletion is implemented which allows direct user feedback.
With the new system enhancement to also support asynchron scenarios, the FE needs to get enhanced to provide specific user feedback in the scenario of a technical user deletion which is asynchron managed.

**Comment by MaximilianHauer** [comment]
issue is implicitly solved by the other stories.
