### ISSUE TITLE
Role Upload does not work during App Release Process when using Firefox

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/portal-frontend#961]
### Current Behavior

When using firefox, during role upload of app release process,
- no roles are extracted and shown
- the drag and drop zone is red while dragging the file into
- the drag and drop zone is disabled after dropping the file into

### Expected Behavior

Role upload should also work in firefox (workaround: use chrome)

### Steps To Reproduce

Use Firefox:
- Trigger App release process
- When asked for roles, download and upload roles again

**Comment by evegufy** [comment]
Hi @tom-rm-meyer-ISST could you please provide the Firefox version where you encountered this issue?
I just tried with 115.3.1esr and I'm not able reproduce it.

**Comment by tom-rm-meyer-ISST** [comment]
> Hi @tom-rm-meyer-ISST could you please provide the Firefox version where you encountered this issue? I just tried with 115.3.1esr and I'm not able reproduce it.

Hi @evegufy, rechecked as I recently updated Firefox. Reproduced with Firefox version 128.0.3.0.

Note: My browser is managed by my organization.

**Comment by evegufy** [comment]
@tom-rm-meyer-ISST can be retested from your end with the next e2e test but closing it now.
