### ISSUE TITLE
[E2E Test 24.08] Service Release Process - Step "Technical Integration" not visible/disappears

### ISSUE THREAD

**Issue by ds-hzimmer** [eclipse-tractusx/portal-frontend#964]
### Current Behavior

For the "App Release Process", accessing a step "Technical Integration" is possible and successful.

For the "Service Release Process", a step "Technical Integration" also exists in the menu overview (with "Lorem Ipsum" boilerplate text).

![Service Management - Service Release Process Steps - 2](https://github.com/user-attachments/assets/c4fd4874-9bb7-451f-9832-73503f5bfb99)

When beginning to enter the necessary information for a new Service, this step is also shown initially when on step 1 "Offer Card" in the breadcrumb navigation as a step 4 "technical Integration" (minor typo with capitalization) 
![Service Release Process - Technical Integration 1 - initially visible](https://github.com/user-attachments/assets/e033e3dd-ec43-4bdd-996c-5d4ee96d7d4f)

But when adding the information in the "Offer Card" and clicking "Save & Submit", this step disappears and then is no longer shown in the breadcrumb navigation menu. After step 3 "Contract & Consent" the next shown step in navigation menu is now "Verify & Submit".

![Service Release Process - Technical Integration 2 - no longer visible](https://github.com/user-attachments/assets/dc0a8a64-200e-433f-82c6-ab8b6f62dfcd)

Thus it is not possible to reach a menu to enter details on "Technical Integration" in the Service Release Process.

### Expected Behavior
According to E2E test case TEST-1260 / CXTM-29 Service Release: Technical Integration such a step should exist:
Portal Service Release Process: Step Contract Consent is finished and next Step Technical Integration can be selected and filled out. 

Thus this may be either a bug in the navigation menu if a step to submit information on "Technical Integration" is required. Or such a "Technical Integration" step **is not relevant** for a Service offering, and all remnants of this should be removed from the menus + navigation?

### Steps To Reproduce
Tested in deployed version for release 24.08 (2.1.0-RC2)

As described above in current behavior.

**Comment by oyo** [comment]
@evegufy @ds-hzimmer in the code the number of steps is variable. The fourth step is only shown if the service type ID  `DATASPACE_SERVICE` is present. So I guess it wasn't in the testing scenario. 

https://github.com/eclipse-tractusx/portal-frontend/blob/release/v2.1.0-RC3/src/components/pages/ServiceReleaseProcess/components/index.tsx#L96-L100
