### ISSUE TITLE
[E2E 24.08] Service Release Process - minor UI limitation: Long Description field in German (de) does not accept German special characters

### ISSUE THREAD

**Issue by ds-hzimmer** [eclipse-tractusx/portal-frontend#965]
### Current Behavior

When trying to add a new service offering for submission, in the Service Details menu the Long Description (de) text field for a new service does not accept **German special characters** Umlauts in caps or small print: Ü, Ö, Ä, ü, ä, ö, as well as ß. 

![Service Details Long Description German - Umlaut nicht akzeptiert](https://github.com/user-attachments/assets/d831de4a-409c-4f0f-998e-9e659909b8f6)

My assumption from the shown error message would be that currently the same filter for allowed characters as for the English Long Description (en) field is used by the system.

That would limit the ability of service providers to describe their offering in German. A workaround is possible by avoiding words with those characters respectively use ue, ae, oe instead, thus only a minor UI issue.

Second finding: Also the explanatory text in this menu above the description fields is a boilerplate “Lorem Ipsum” text, which should be either removed or updated to the actual text at some point.

### Expected Behavior
If not limited for technical reasons, it should be possible to use those special German characters in all German language fields

### Steps To Reproduce
Tested with deployed version for release 24.08 (2.1.0-RC2)

Encountered in menu Service Release Process - Submit for Review - Long Description (de) field.
Potentially this limitation also occurs in other German language description fields.

**Comment by JordanGerada3** [comment]
I would like to pick up this topic. @typecastcloud
