### ISSUE TITLE
App Release | App manager is allowed to upload duplicate roles

### ISSUE THREAD

**Issue by ss-nikunj** [eclipse-tractusx/portal-frontend#969]
These are the following backend issues. (https://github.com/eclipse-tractusx/portal-backend/issues/868)

**Issue #1**

- Users are allowed to upload the same CSV file with the same Role values any number of times, resulting in the same roles being repeated multiple times in the app's role list.
- **Current Behavior:** The same role being repeated n times in the list and also does not allow to delete of the role.
- **Expected Behavior:** It should ignore the duplicate role and also deletion of each recently uploaded should be working.

**Steps To Reproduce:**
1. Login to the Portal as App Manager
2. Register an App
3. Add/Input all the required data
4. Under Technical integration --> Download the CSV template and then upload it
5. Delete the recently uploaded CSV template and Upload it again (N Times)

**Issue# 2**

- When the User deletes the uploaded file of roles then uploaded roles are not removed from the list.
- **Current Behavior:** The Uploaded file was removed successfully but its associated roles remain as it is and due to that duplication of roles is happening in the section.
- **Expected Behavior:** The Roles file should be deleted and its associated roles should be removed.

**Steps To Reproduce:**

1. Login to the Portal as App Manager
2. Register an app
3. Add/Input all the required data
4. Under Technical integration --> Download CSV template and then upload it back
5. Delete the recently uploaded CSV template
6. The roles will be unchanged. (The attached file's roles should be removed )

**Proposed Solutions**

1. While Onboarding a New App: At the Technical Integration step 
   **Backend:** API exists to upload the App Roles but the backend would need to change the API and ignore the duplicate role values while uploading the roles to the server

2. While Onboarding a New App: Delete all roles that were recently uploaded by the `.csv` file
**Frontend:** Frontend would be integrating this API and passing all the recently uploaded role's IDs to the API to delete the roles

3. While updating the **Onboarded App**: Delete all the roles that were recently uploaded by the .csv file
**Frontend:** Frontend would have to identify the recently uploaded roles (because in case of an update, already assigned roles would already be part of the app) and then pass the recently uploaded role IDs to the API to delete them from the database

**Comment by MaximilianHauer** [comment]
@ss-nikunj  can we close this ? respective PR is merged
