### ISSUE TITLE
Fix CodeQL finding - useless conditional

### ISSUE THREAD

**Issue by oyo** [eclipse-tractusx/portal-frontend#975]
### Current Behavior
A CodeQL scan found a conditional that is always true

### Expected Behavior
Conditionals don't make sense where their value can have only one value

### Steps To Reproduce
Commit: https://github.com/eclipse-tractusx/portal-frontend/commit/7d46955d68eafeac4f9c498e566abcc7d22376f8
PR https://github.com/eclipse-tractusx/portal-frontend/pull/974
Scan result: https://sonarcloud.io/project/issues?sinceLeakPeriod=true&issueStatuses=OPEN%2CCONFIRMED&pullRequest=974&id=eclipse-tractusx_portal-frontend&open=AZD-U7eWt2XPuu9WImA6

**Comment by MaximilianHauer** [comment]
fine
