### ISSUE TITLE
Partner network | BPDM service is not accessible - Implement new API

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#980]
### Current Behavior

 The Partner network doesn't list Partners for most roles (except CX Admin) due to a 403 error:

![image](https://github.com/user-attachments/assets/57c6bcc0-05b8-44ef-a5d7-0980f54b626c)

In the Ticket eclipse-tractusx/portal-iam#132 it was revealed that the proper way to solve this is to connect to annew API from BPDM:

>  Since version 6 of the API we introduced the members endpoint which returns only the Catena-X business partner member data: 
> pool/v6/members/legal-entities/search
> So from the BPDM side this behaviour is expected, but the Portal would need to integrate the members endpoint instead.

https://github.com/eclipse-tractusx/portal-iam/issues/132#issuecomment-2247167501

### Expected Behavior

We should be able to access the BPDM service with an appropriate role.

### Steps To Reproduce

Check the Partner Network in the portal or try to access the BPDM service APIs.

Detected in v2.0.0

**Comment by evegufy** [comment]
Should fix the following issues:
- Portal's Partner Network page does not currently show business partner member data due to an authorization issue
- Currently not possible to add company's site and address business partners over the Portal due to authorization issue

**Comment by ybidois** [comment]
Hi @oyo 👋 Any timeline when you plan to take this? Could we help you on this ticket? We'd like to solve this for the customers in the next 2 weeks. We have dev capacity to get it done. We would then cherry-pick it for our next release in prod.

**Comment by oyo** [comment]
Hi @ybidois - sorry we are currently a little bit short of dev capacity. We just discussed this in our team and reassigned it to @manojava-gk who has done a lot on that page

**Comment by ybidois** [comment]
> Hi @ybidois - sorry we are currently a little bit short of dev capacity. We just discussed this in our team and reassigned it to @manojava-gk who has done a lot on that page

Thanks for the update @oyo!

**Comment by MaximilianHauer** [comment]
@ybidois  we plan this for our intermediate release 2.2.0. plan is to get 2.2.0 out as soon as possible

**Comment by MaximilianHauer** [comment]
tested and approved
