### ISSUE TITLE
sig#803: enhance frontend technical user by a new status "pending deletion"

### ISSUE THREAD

**Issue by MaximilianHauer** [eclipse-tractusx/portal-frontend#988]
### Description

backend will introduce a new status in the `api/administration/serviceaccount/owncompany/serviceaccounts` api 
called `PENDING_DELETION`
this tasks aims to fetch this new status from the backend api and then display it properly in the status column.
This is an enhancement of this ticket and therefor should be used as an orientation on the development effort. 
+ #944 

### Acceptance Criteria
**Implementation:**
- [ ] Fetch the new status from the backend api 
- [ ] Ensure that the `PENDING_DELETION` status is reflected in the frontend respectively 
- [ ] Ensure that the `PENDING_DELETION` status has the same color coding as `PENDING`

**Documentation:**
- [ ]  Update the Technical User Management page documentation to include the new status.

**Comment by evegufy** [comment]
@MaximilianHauer I suggest to close this isse

**Comment by MaximilianHauer** [comment]
approved
