### ISSUE TITLE
App Manager | 'App Manager' user has access to 'Service Subscription Mgt' page

### ISSUE THREAD

**Issue by tfjanjua** [eclipse-tractusx/portal-frontend#991]
### Current Behavior
`Service Subscription Mgt` page is accessible to the `App Manager` user because `App Manager` user has role `activate_subscription` and `activate_subscription` is also assigned to `Service Subscription Mgt` page.

### Expected Behavior
`App Manager` user should not have the access of `Service Subscription Mgt` page

### Steps To Reproduce
- Login to the portal as a App Manager user
- After login, type `servicesubscription` at the end of the url, you will see `Service Subscription Mgt` page

### Findings
1. I see the page and roles assignment for `Service Subscription Mgt` page on frontend and I found that `Service Subscription Mgt` page has `activate_subscription` role but the variable name of role is: `SERVICE_SUBSCRIPTION_MANAGEMENT` so, this seems like a wrong role associated with wrong variable

2. If we take example of `Service Management` main menu so this main menu is clickable and it has `add_service_offering` role and `Service Management` main menu has following sub menus and their associated roles:

`Service Overview`                -> `add_service_offering`
`Service Release Process`    -> `add_service_offering`
`Service Subscription Mgt`   -> `activate_subscription`
`Admin Board`                        -> `approve_service_release`

Now, if a user (like App Manager) does not has `add_service_offering` role so user would not be able to complete `Service Management` main menu but if user has any other role from the sub menu item (like App Manager has `activate_subscription`) so, that sub menu item will not be visible but it would accessible if we try to access it explicitly by url.

### Proposed Solution
1. It seems like `SERVICE_SUBSCRIPTION_MANAGEMENT` variable has wrong value `activate_subscription` and if so, so we can set the correct value.
2. We can apply a condition on Main Manu item `Service Management` that if a user has any one role associated with the sub menu items, then Main Menu item should be visible including required sub menu items.

**Comment by tfjanjua** [comment]
Hi @evegufy | @oyo | @MaximilianHauer , we have found one role which is specific to the Service Manager `service_management` and it seems like we can use this `service_management` role for `SERVICE_SUBSCRIPTION_MANAGEMENT` variable (this variable exists in src/types/Constants.cs file in frontend repo).

please let me know if there any other way to look at this issue after checking all the details from above mentioned Findings heading.

**Comment by MaximilianHauer** [comment]
@tfjanjua thank you for the hint we will have a look

**Comment by MaximilianHauer** [comment]
based on the current implementation logic 

1. to show "Service Management" the user needs to have the "add_service_offering" role
2. to see the "Service Subscription Mgt" you need to have "service_management" 

if you create the pr please assign @manojava-gk and @phil for reviewer
